<?php
use Zertifizierungstool\Model\Antwort;
use Zertifizierungstool\Model\Frage;
?>
<script type="text/javascript">
<!-- Doku //-->
function showFormMC() {
	<?php 
	$frage   = new Frage();
	if ($mode == PruefungController::editFragen) {
		$antworten = Antwort::loadList($frageToEdit->getId());
			
		$frage = $frageToEdit;
		?>

		AntwortAnzahl = <?=count($antworten);?>
	<?php } ?>
	
	document.getElementById("formular").innerHTML = formMC;
}

function showFormTF() {
	<?php 
	$antwort = new Antwort();
	$frage   = new Frage();
	if ($mode == PruefungController::editFragen) {
		$antworten = Antwort::loadList($frageToEdit->getId());
		
		if (!empty($antworten[0])) $antwort = $antworten[0];
		$frage = $frageToEdit;
	} ?>

	document.getElementById("formular").innerHTML = formTF;
}

function newAntwort() {
	AntwortAnzahl = AntwortAnzahl + 1;

	document.getElementById(AntwortAnzahl).innerHTML =
		'<input type="text"     name="antwort_text'    + AntwortAnzahl + '" required> ' +
		'<input type="checkbox" name="antwort_checked' + AntwortAnzahl + '">  ' +
		'<button type="button" onclick="deleteAntwort(' + AntwortAnzahl + ')"> - </button>' +
		'<p id="' + (AntwortAnzahl + 1) +'"></p>';
}

function deleteAntwort(nummer) {
	for (i = nummer; i <= AntwortAnzahl; i++) {
		document.getElementById(i).innerHTML = document.getElementById(i + 1).innerHTML; 
	}

	AntwortAnzahl = AntwortAnzahl - 1;
}
</script>


<?php 
	// Alle Schlüssel aus dem Request-Array auslesen, die sich auf die Antworten beziehen
	$id_keys	= preg_grep('/^antwort_id[\d]*/',      array_keys($_REQUEST));
	$text_keys  = preg_grep('/^antwort_text[\d]*/',    array_keys($_REQUEST));
	$check_keys = preg_grep('/^antwort_checked[\d]*/', array_keys($_REQUEST));
?>


	
	
	
	
	Frage:<br>
	<textarea rows="3" cols="50" name="frage_text" form="frageForm" required> <?=$frage->getText()?> </textarea>
	<form method="POST" id="frageForm">
	
	Punkte:
	<input type="number" name="punkte" min="0" required value="<?=$frage->getPunkte()?>"> <br>
	
	
	True/False:
	<input type="hidden" name="frage_typ"  readonly="readonly" value="TF">
	<input type="hidden" name="antwort_id" readonly="readonly" value="<?=$antwort->getId()?>">
	<input type="radio"  name="tf" value="true" <?php if ($antwort->getStatus() == 1) echo "checked";?>> Wahr  <br>
	<input type="radio"  name="tf" value="false"<?php if ($antwort->getStatus() == 0) echo "checked";?>> Falsch<br>
	
	Multiple-Choice:
	<input type="hidden" name="frage_typ" readonly="readonly" value="MC">
	<?php
	$i = 1;
	foreach ($antworten as $antwort) { ?>
		<input type="hidden"   name="antwort_id<?=$i?>"   value="<?=$antwort->getId()  ?>" readonly="readonly">
		<input type="text"     name="antwort_text<?=$i?>" value="<?=$antwort->getText()?>" required >
		<input type="checkbox" name="antwort_checked<?=$i?>" <?php if ($antwort->getStatus() == 1) echo "checked"?>>
		<a href="<?= $this->url('frage', ['action' => 'deleteAntwort', 'id' => $antwort->getId()])?>"><button type="button"> - </button></a>
	<?php 
		$i++;
	}
	?>
	'<p id="' + (AntwortAnzahl + 1) + '"></p>'
	<button type="button" onclick="newAntwort()">Antwortoption hinzufügen</button>
	
	
	
	
	
	
	
	


	
	
	
	
	
	
	
	<input type="hidden" name="id" 		 	readonly="readonly">
	<input type="hidden" name="pruefung_id" readonly="readonly" value="<?=$frage->getPruefungId()?>">
	<input type="submit" name="speichernFrage" value="Speichern">
	<input type="reset" value="Felder zur&uuml;cksetzen">
	</form>