<?php
use Zertifizierungstool\Model\Frage;
use Zertifizierungstool\Model\Antwort;
use Zertifizierungstool\Model\Pruefung;
use Zertifizierungstool\Controller\PruefungController;

if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}

if ($mode == PruefungController::PRUEFUNG) {
	$pruefSaveButton = "submit";
	$pruefBackground = 'style="background-color: aqua;"';
	$frageBackground = 'style="background-color: gray;"';
	$frageDisabled   = 'disabled "disabled"';
	$pruefReadonly	 = '';
} else {
	$pruefReadonly = 'readonly = "readonly" disabled';
	$pruefSaveButton = "hidden";
	$pruefBackground = 'style="background-color: gray;"';
	$frageBackground = 'style="background-color: aqua;"';
	$frageDisabled	 = '';
}
?>
<style>
#KopfdatenPruefung {
	position: relative;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 100%;
	padding: 2em;
	}


#FragenListe {
	float:left;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 40%;
	padding: 2em;
	}

#Frage {
	padding: 2em;
	margin-left: 40%;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 60%;
	}
	
input[type=number]{
	width: 4em;
}
</style>

<script type="text/javascript">
	var AntwortAnzahl;

	var frage_text;
	var frage_punkte;

	var antwort_id;
	var antwort_text;
	var antwort_status;
	
	var formStart =
		'Frage: <br> <textarea rows="3" cols="50" name="frage_text" form="frageForm" required>' + frage_text + '</textarea>' +
		'<form method="POST" id="frageForm">' + 
			'Punkte: <input type="number" name="punkte" min="0" required value="' + frage_punkte + '"> <br>';

	var formEnd = 
		'<input type="hidden" name="id" 		 readonly="readonly">' +
		'<input type="hidden" name="pruefung_id" readonly="readonly" value="<?=$pruefung->getId()?>">' +
		'<input type="submit" name="speichernFrage" value="Speichern">' +
		'<input type="reset" value="Felder zur&uuml;cksetzen">' +
		'</form> <br>';

	var formMC = 
		'Multiple Choice - Frage: <br>' + formStart +

		'<input type="hidden" name="frage_typ" readonly="readonly" value="MC">' +
		
		'Antwortm&ouml;glichkeiten:<br>' +
		'<input type="text"     name="antwort_text1" required> ' +
		'<input type="checkbox" name="antwort_checked1">' +
		
		'<p id="ant2"></p>' +

		'<button type="button" onclick="newAntwort()">Neue Antwort</button>' +		

		formEnd;
		
	var formTF = 
		'True / False - Frage: <br>' + formStart +

		'<input type="hidden" name="frage_typ" readonly="readonly" value="TF">' +
		
		'<input type="radio" name="tf" value="true" checked> Wahr<br>' +
		'<input type="radio" name="tf" value="false"> Falsch<br>' +
		
		formEnd;
	
	function showFormMC() {
		AntwortAnzahl = 1;
		<?php if ($mode == PruefungController::createFragen) {?>
		document.getElementById("formular").innerHTML = formMC;

		<?php } elseif ($mode == PruefungController::editFragen) { ?>
		frage_text 	 = <?=$frageToEdit->getText()  ?>;
		frage_punkte = <?=$frageToEdit->getPunkte()?>;
		<?php $antworten = Antwort::loadList($frageToEdit->getId()); ?>
		
		document.getElementById("formular").innerHTML = formMC;
		<?php }?>
	}

	function showFormTF() {
		<?php if ($mode == PruefungController::createFragen) {?>
		document.getElementById("formular").innerHTML = formTF;

		<?php } elseif ($mode == PruefungController::editFragen) { ?>
		frage_text 	 = <?=$frageToEdit->getText()  ?>;
		frage_punkte = <?=$frageToEdit->getPunkte()?>;
		<?php $antworten = Antwort::loadList($frageToEdit->getId()); ?>
		
		document.getElementById("formular").innerHTML = formTF;
		<?php }?>
	}

	function newAntwort() {
		AntwortAnzahl = AntwortAnzahl + 1;
		
		var aktStelle = AntwortAnzahl;
		var neuStelle = AntwortAnzahl + 1;
		
		document.getElementById("ant" + aktStelle).innerHTML =
			'<input type="text"     name="antwort_text'    + AntwortAnzahl + '" required> ' +
			'<input type="checkbox" name="antwort_checked' + AntwortAnzahl + '">  ' +
			'<button type="button" onclick="deleteAntwort(' + AntwortAnzahl + ')"> - </button>' +
			'<p id="ant' + neuStelle +'"></p>';
	}


	function deleteAntwort(nummer) {
		for (i = nummer; i <= AntwortAnzahl; i++) {
			document.getElementById("ant" + i).innerHTML = document.getElementById("ant" + (i+1)).innerHTML; 
		}

		AntwortAnzahl = AntwortAnzahl - 1;
	}

</script>



<h1>Pr&uuml;fung anlegen/bearbeiten</h1>


<div id="KopfdatenPruefung" <?=$pruefBackground?>>
<h2>Kopfdaten</h2>
<form method="POST">	
	<table>
		<tr><td>Pr&uuml;fungsname</td><td><input type="text"   name="name"     <?=$pruefReadonly?> required value="<?=$pruefung->getName()    ?>" ></td></tr>
		<tr><td>Termin		 	 </td><td><input type="date"   name="termin"   <?=$pruefReadonly?> required value="<?=$pruefung->getTermin()  ?>" ></td></tr>
		<tr><td>Cutscore (%) 	 </td><td><input type="number" name="cutscore" <?=$pruefReadonly?> required value="<?=$pruefung->getCutscore() * 100?>" min="0" max="100"></td></tr>
	</table>
	
	<input type="hidden" name="pruefid"  readonly="readonly" value="<?=$pruefung->getId()?>" >
	<input type="hidden" name="kursid"   readonly="readonly" value="<?=$pruefung->getKursId()?>" >
	
	<input type="<?=$pruefSaveButton?>" name="speichernPruefung" value="Zu den Fragen">
</form>
</div>



<div id="FragenListe" <?=$frageBackground?>>
	<h3>Angelegte Fragen</h3>
	<table>
	<?php
		if (empty($fragen)) {
			echo "<tr><td>(leer)</tr></td>";
		} else {
		foreach ($fragen as $frage) { ?>
			<tr><td><?=$frage->getText()?></td><td><?=$frage->getTyp()?></td><td><a href="<?= $this->url('frage', ['action' => 'edit', 'id' => $frage->getId()]) ?>"><button type="button" <?=$frageDisabled?>>Bearbeiten</button></a></td><td><a href="<?= $this->url('frage', ['action' => 'delete', 'id' => $frage->getId()]) ?>"><button type="button" <?=$frageDisabled?>>L&ouml;schen</button></a></td>			
	<?php
		}}
	?>
		
	</table>
	
	<a href="<?= $this->url('frage', ['action' => 'create', 'id' => $pruefung->getId()])  ?>"><button type="button" <?=$frageDisabled?>>Neue Frage Anlegen</button></a>
	<a href="<?= $this->url('pruefung', ['action' => 'edit', 'id' => $pruefung->getId()]) ?>"><button type="button" <?=$frageDisabled?>>Kopfdaten der Pr&uuml;fung bearbeiten</button></a>
</div>

<div id="Frage" <?=$frageBackground?>>
<?php if ($mode == PruefungController::createFragen) { ?>

<h3>Frage anlegen</h3>
	<table><tr><td><button type="button" onclick="showFormMC()">Multiple Choice</button></td><td><button type="button" onclick="showFormTF()">True / False</button></td></tr></table>
	<p id="formular">W&auml;hlen Sie einen Frage-Typ aus, um die Eingabemaske anzuzeigen.</p>

<?php } elseif ($mode == PruefungController::editFragen) { ?>
<h3>Frage bearbeiten</h3>
	Frage: <br> <textarea rows="3" cols="50" name="frage_text" form="frageForm" required><?=$frageToEdit->getText()?></textarea>
	<form method="POST" id="frageForm">
	<br>Punkte <input type="number" name="punkte" min="0" required value="<?=$frageToEdit->getPunkte()?>"><br>

	
	<?php 
	$antworten = Antwort::loadList($frageToEdit->getId());
	
	if ($frageToEdit->getTyp() == "TF") { ?>
		<input type="hidden" name="frage_typ" readonly="readonly" value="TF">
		<input type="radio" name="tf" value="true"  <?php if ($antworten[0]->getStatus() == 1) echo "checked";?>> Wahr<br>
		<input type="radio" name="tf" value="false" <?php if ($antworten[0]->getStatus() == 0) echo "checked";?>> Falsch<br>
		<input type="hidden"   name="antwort_id" value="<?=$antworten[0]->getId()?>">
	
	<?php } else {
		echo '<input type="hidden" name="frage_typ" readonly="readonly" value="MC"> Antwortm&ouml;glichkeiten:';
		$i = 1;
		foreach ($antworten as $antwort) { echo '<br>' ?>
		<input type="text"     name="antwort_text<?=$i?>" required value="<?=$antwort->getText()?>">
		<input type="checkbox" name="antwort_checked<?=$i?>" <?php if ($antwort->getStatus() == 1) echo "checked"?>>
		<input type="hidden"   name="antwort_id<?=$i?>" value="<?=$antwort->getId()?>">
		<a href="<?= $this->url('frage', ['action' => 'deleteAntwort', 'id' => $antwort->getId()])?>"><button type="button"> - </button></a>
	<?php 
		}
	}
	?>
	
	<input type="hidden" name="id" 		    readonly="readonly" value="<?=$frageToEdit->getId()?>">
	<input type="hidden" name="pruefung_id" readonly="readonly" value="<?=$frageToEdit->getPruefungId()?>">
	<input type="submit" name="speichernFrage" value="Speichern">
	<input type="reset" value="Felder zur&uuml;cksetzen">
	</form>
<?php } ?>
	
	
	
</div>


<br>
<a href="<?= $this->url('pruefung', ['action' => 'overview', 'id' => $pruefung->getKursId()])?>"><button type="button">Zur&uuml;ck zur Pr&uuml;fungsliste</button></a>

















