<?php
use Zertifizierungstool\Model\Frage;
use Zertifizierungstool\Model\Antwort;
use Zertifizierungstool\Model\Pruefung;
use Zertifizierungstool\Controller\PruefungController;

if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}

if ($mode == PruefungController::PRUEFUNG) {
	$pruefSaveButton = "submit";
	$pruefBackground = 'style="background-color: aqua;"';
	$frageBackground = 'style="background-color: gray;"';
	$frageDisabled   = 'disabled "disabled"';
	$pruefReadonly	 = '';
} else {
	$pruefReadonly = 'readonly = "readonly" disabled';
	$pruefSaveButton = "hidden";
	$pruefBackground = 'style="background-color: gray;"';
	$frageBackground = 'style="background-color: aqua;"';
	$frageDisabled	 = '';
}
?>
<style>
#KopfdatenPruefung {
	position: relative;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 100%;
	padding: 2em;
	}


#FragenListe {
	float:left;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 40%;
	padding: 2em;
	}

#Frage {
	padding: 2em;
	margin-left: 40%;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 60%;
	}
	
input[type=number]{
	width: 4em;
}
</style>

<script type="text/javascript">
<!-- Doku //-->
	var AntwortAnzahl = 0;

	var frage_text = '';
	var frage_punkte = 0;
	var frage_id = '';
	var pruefung_id = '';
	
	/* var formStart =  
		'Frage:<br>'
		+ '<textarea rows="3" cols="50" name="frage_text" form="frageForm" required> ' + frage_text + '</textarea>'
		+ '<form method="POST" id="frageForm">'
		
		+ 'Punkte: '
		+ '<input type="number" name="punkte" min="0" required value="' + frage_punkte + '"> <br>';

	var formEnd = 
		  '<input type="hidden" name="id" 		   readonly="readonly" value="' + frage_id + '">'
		+ '<input type="hidden" name="pruefung_id" readonly="readonly" value="' + pruefung_id + '">'
		+ '<input type="submit" name="speichernFrage" value="Speichern">'
		+ '<input type="reset" value="Felder zur&uuml;cksetzen">'
		+ '</form><br>';
 */
	function showFormMC() { 
		var type = 'MC';
		showForm(type); }
	function showFormTF() { showForm('TF'); }
	
	function showForm(type) {
		document.getElementById("formular").innerHTML = 'testtest Typ: ' + type;
	}
	
</script>



<h1>Pr&uuml;fung anlegen/bearbeiten</h1>


<div id="KopfdatenPruefung" <?=$pruefBackground?>>
<h2>Kopfdaten</h2>
<form method="POST">	
	<table>
		<tr><td>Pr&uuml;fungsname</td><td><input type="text"   name="name"     <?=$pruefReadonly?> required value="<?=$pruefung->getName()    ?>" ></td></tr>
		<tr><td>Termin		 	 </td><td><input type="date"   name="termin"   <?=$pruefReadonly?> required value="<?=$pruefung->getTermin()  ?>" ></td></tr>
		<tr><td>Cutscore (%) 	 </td><td><input type="number" name="cutscore" <?=$pruefReadonly?> required value="<?=$pruefung->getCutscore() * 100?>" min="0" max="100"></td></tr>
	</table>
	
	<input type="hidden" name="pruefid"  readonly="readonly" value="<?=$pruefung->getId()?>" >
	<input type="hidden" name="kursid"   readonly="readonly" value="<?=$pruefung->getKursId()?>" >
	
	<input type="<?=$pruefSaveButton?>" name="speichernPruefung" value="Zu den Fragen">
</form>
</div>



<div id="FragenListe" <?=$frageBackground?>>
	<h3>Angelegte Fragen</h3>
	<table>
	<?php
		if (empty($fragen)) {
			echo "<tr><td>(leer)</tr></td>";
		} else {
		foreach ($fragen as $frage) { ?>
			<tr><td><?=$frage->getText()?></td><td><?=$frage->getTyp()?></td><td><a href="<?= $this->url('frage', ['action' => 'edit', 'id' => $frage->getId()]) ?>"><button type="button" <?=$frageDisabled?>>Bearbeiten</button></a></td><td><a href="<?= $this->url('frage', ['action' => 'delete', 'id' => $frage->getId()]) ?>"><button type="button" <?=$frageDisabled?>>L&ouml;schen</button></a></td>			
	<?php
		}}
	?>
		
	</table>
	
	<a href="<?= $this->url('frage', ['action' => 'create', 'id' => $pruefung->getId()])  ?>"><button type="button" <?=$frageDisabled?>>Neue Frage Anlegen</button></a>
	<a href="<?= $this->url('pruefung', ['action' => 'edit', 'id' => $pruefung->getId()]) ?>"><button type="button" <?=$frageDisabled?>>Kopfdaten der Pr&uuml;fung bearbeiten</button></a>
</div>



<div id="Frage" <?=$frageBackground?>>
<?php if ($mode == PruefungController::createFragen) { ?>
	<h3>Frage anlegen</h3>
	<button type="button" onclick="showFormMC()">Multiple Choice</button>
	<button type="button" onclick="showFormTF()">True / False   </button>

<?php } elseif ($mode == PruefungController::editFragen) { ?>
	<h3>Frage bearbeiten</h3>
	<button type="button" onclick="showFormMC()">Multiple Choice</button>
	<button type="button" onclick="showFormTF()">True / False   </button>


<?php } ?>
	
<p id="formular"></p>
</div>


<br>
<a href="<?= $this->url('pruefung', ['action' => 'overview', 'id' => $pruefung->getKursId()])?>"><button type="button">Zur&uuml;ck zur Pr&uuml;fungsliste</button></a>

















