<?php
use Zertifizierungstool\Model\Frage;
use Zertifizierungstool\Model\Antwort;
use Zertifizierungstool\Model\Pruefung;
use Zertifizierungstool\Controller\PruefungController;

if (isset($errors)) {
	foreach ($errors as $err) {
		echo "Fehler: " . $err . "<br>";
	}
}

if ($mode == PruefungController::PRUEFUNG) {
	$pruefSaveButton = "submit";
	$pruefBackground = 'style="background-color: aqua;"';
	$frageBackground = 'style="background-color: gray;"';
	$frageDisabled   = 'disabled "disabled"';
	$pruefReadonly	 = '';
} else {
	$pruefReadonly = 'readonly = "readonly" disabled';
	$pruefSaveButton = "hidden";
	$pruefBackground = 'style="background-color: gray;"';
	$frageBackground = 'style="background-color: aqua;"';
	$frageDisabled	 = '';
}
?>
<style>
#KopfdatenPruefung {
	position: relative;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 100%;
	padding: 2em;
	}


#FragenListe {
	float:left;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 40%;
	padding: 2em;
	}

#Frage {
	padding: 2em;
	margin-left: 40%;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 60%;
	}
	
input[type=number]{
	width: 4em;
}
</style>

<script type="text/javascript">
<!-- Doku //-->
	var AntwortAnzahl = 0;

	var frage_text = '';
	var frage_punkte = 0;
	var frage_id = '';
	var pruefung_id = '';
	
	var formStart =  
		'Frage:<br>'
		+ '<textarea rows="3" cols="50" name="frage_text" form="frageForm" required> ' + frage_text + '</textarea>'
		+ '<form method="POST" id="frageForm">'
		
		+ 'Punkte: '
		+ '<input type="number" name="punkte" min="0" required value="' + frage_punkte + '"> <br>';

	var formEnd = 
		  '<input type="hidden" name="id" 		   readonly="readonly" value="' + frage_id + '">'
		+ '<input type="hidden" name="pruefung_id" readonly="readonly" value="' + pruefung_id + '">'
		+ '<input type="submit" name="speichernFrage" value="Speichern">'
		+ '<input type="reset" value="Felder zur&uuml;cksetzen">'
		+ '</form><br>';
 
	function showFormMC() { showForm('MC'); }
	function showFormTF() { showForm('TF'); }
	
	function showForm(type) {
		<?php 
		$frage   = new Frage();
		$antworten = array();
		array_push($antworten, new Antwort());
		
		if ($mode == PruefungController::editFragen) {
			$antworten = Antwort::loadList($frageToEdit->getId());			
			$frage = $frageToEdit;
			
		}
		$antwort = $antworten[0]; // Für TF
		?>

		AntwortAnzahl = <?=count($antworten)?>;
		frage_text 	  = <?=$frage->getText()?>;
		frage_punkte  = <?=$frage->getPunkte()?>;
		frage_id	  = <?=$frage->getId()?>;
		pruefung_id   = <?=$frage->getPruefungId()?>;

		var form = '';
		
		switch (type) {
		case 'MC':
			form +=
				'<input type="hidden" name="frage_typ" readonly="readonly" value="MC">'
				
				<?php
				$i = 1;
				foreach ($antworten as $antwort) { ?>
				+ '<input type="hidden"   name="antwort_id<?=$i?>"   value="<?=$antwort->getId()  ?>" readonly="readonly">'
				+ '<input type="text"     name="antwort_text<?=$i?>" value="<?=$antwort->getText()?>" required >'
				+ '<input type="checkbox" name="antwort_checked<?=$i?>" <?php if ($antwort->getStatus() == 1) echo "checked";?>>'
				
				+ '<a href="<?= $this->url('frage', ['action' => 'deleteantwort', 'id' => $antwort->getId()])?>"><button type="button"> - </button></a><br><br>'

				
				<?php 
					$i++;
				}
				?>

				+ '<p id="antwortenListe"></p>'
				+ '<br><button type="button" onclick="newAntwort()">Antwortoption hinzufügen</button>';
				
			break;

		case 'TF':
			form +=
				  '<input type="hidden" name="frage_typ"  readonly="readonly" value="TF">'
				+ '<input type="hidden" name="antwort_id" readonly="readonly" value="<?=$antwort->getId()?>">'
				+ '<input type="radio"  name="tf" 		  value="true" <?php if ($antwort->getStatus() == 1) echo "checked";?>> Wahr  <br>'
				+ '<input type="radio"  name="tf" 	 	  value="false"<?php if ($antwort->getStatus() == 0) echo "checked";?>> Falsch<br>';
			
			break;
		default:
			form += 'Kein Typ ausgewählt';
			break;
		}

		document.getElementById("formular").innerHTML = formStart + form + formEnd;
	}
	
	function newAntwort() {
		AntwortAnzahl = AntwortAnzahl + 1;

		var neue_antwort	= 
			  '<input type="text"     name="antwort_text'    + AntwortAnzahl + '" required> '
			+ '<input type="checkbox" name="antwort_checked' + AntwortAnzahl + '">  '
		
			+ '<button type="button" onclick="deleteAntwort(' + AntwortAnzahl + ')"> - </button>';

			
		var new_para = document.createElement("p"); 
		new_para.id = AntwortAnzahl;                
		new_para.innerHTML = neue_antwort;
		                           
		document.getElementById("antwortenListe").appendChild(new_para);
	}


	function deleteAntwort(nummer) {
		document.getElementById("antwortenListe").removeChild(nummer);
	}
	
</script>



<h1>Pr&uuml;fung anlegen/bearbeiten</h1>


<div id="KopfdatenPruefung" <?=$pruefBackground?>>
<h2>Kopfdaten</h2>
<form method="POST">	
	<table>
		<tr><td>Pr&uuml;fungsname</td><td><input type="text"   name="name"     <?=$pruefReadonly?> required value="<?=$pruefung->getName()    ?>" ></td></tr>
		<tr><td>Termin		 	 </td><td><input type="date"   name="termin"   <?=$pruefReadonly?> required value="<?=$pruefung->getTermin()  ?>" ></td></tr>
		<tr><td>Cutscore (%) 	 </td><td><input type="number" name="cutscore" <?=$pruefReadonly?> required value="<?=$pruefung->getCutscore() * 100?>" min="0" max="100"></td></tr>
	</table>
	
	<input type="hidden" name="pruefid"  readonly="readonly" value="<?=$pruefung->getId()?>" >
	<input type="hidden" name="kursid"   readonly="readonly" value="<?=$pruefung->getKursId()?>" >
	
	<input type="<?=$pruefSaveButton?>" name="speichernPruefung" value="Zu den Fragen">
</form>
</div>



<div id="FragenListe" <?=$frageBackground?>>
	<h3>Angelegte Fragen</h3>
	<table>
	<?php
		if (empty($fragen)) {
			echo "<tr><td>(leer)</tr></td>";
		} else {
		foreach ($fragen as $frage) { ?>
			<tr><td><?=$frage->getText()?></td><td><?=$frage->getTyp()?></td><td><a href="<?= $this->url('frage', ['action' => 'edit', 'id' => $frage->getId()]) ?>"><button type="button" <?=$frageDisabled?>>Bearbeiten</button></a></td><td><a href="<?= $this->url('frage', ['action' => 'delete', 'id' => $frage->getId()]) ?>"><button type="button" <?=$frageDisabled?>>L&ouml;schen</button></a></td>			
	<?php
		}}
	?>
		
	</table>
	
	<a href="<?= $this->url('frage', ['action' => 'create', 'id' => $pruefung->getId()])  ?>"><button type="button" <?=$frageDisabled?>>Neue Frage Anlegen</button></a>
	<a href="<?= $this->url('pruefung', ['action' => 'edit', 'id' => $pruefung->getId()]) ?>"><button type="button" <?=$frageDisabled?>>Kopfdaten der Pr&uuml;fung bearbeiten</button></a>
</div>



<div id="Frage" <?=$frageBackground?>>
<?php if ($mode == PruefungController::createFragen) { ?>
	<h3>Frage anlegen</h3>
	<button type="button" onclick="showFormMC()">Multiple Choice</button>
	<button type="button" onclick="showFormTF()">True / False   </button>

<?php } elseif ($mode == PruefungController::editFragen) { ?>
	<h3>Frage bearbeiten</h3>
	<button type="button" onclick="showFormMC()">Multiple Choice</button>
	<button type="button" onclick="showFormTF()">True / False   </button>


<?php } ?>
	
<p id="formular"></p>
</div>


<br>
<a href="<?= $this->url('pruefung', ['action' => 'overview', 'id' => $pruefung->getKursId()])?>"><button type="button">Zur&uuml;ck zur Pr&uuml;fungsliste</button></a>

















