<?php 


if (!empty($errors)) {
	?>
	<div class="alert alert-danger" role="alert">
	<?php 
	echo '<font color="red"><h2><b>Sie wollten eine Pr&uuml;fung ablegen. Dabei sind folgende Fehler aufgetreten:</b></h2></font><br><br>';
			
	foreach ($errors as $err) {
		echo "<br>" . $err;
	}
	?>
	</div>
	<?php 
}
?>

<a href="<?= $this->url('pruefung', ['action' => 'overview', 'id' => $kursid])?>"><button type="button" class="btn btn-default">zur&uuml;ck zur Pr&uuml;fungs&uuml;bersicht</button></a><br><br>