<h1>Kurs anlegen</h1>

<?php

    if(!isset($message)){
        echo "Daten konnten nicht gespeichert werden!";
    }
    else {
        header("url = /user/home");
        echo "Die Speicherung der Daten war erfolgreich!";
        
    }
		
?>


<form action="anlegen" method="POST">
    <table>
        <tr><td> Kursname:</td>
            <td><input name='kursname' size="40" maxlength="250" type='text' required></td></tr>
        <tr><td> Kursstart:</td>
            <td><input name='kursstart' size="40" maxlength="250" type='date' required></td></tr>
        <tr><td> Kursende:</td>
            <td><input name='kursende' size="40" maxlength="250" type='date' required></td></tr>
        <tr><td> Sichtbarkeit:</td>
            <td><select name="sichtbarkeit">
			<option value="ja">sichtbar</option>
			<option value="nein" selected>nicht sichtbar</option>
                </select></td></tr>
    </table>
    <input type = "submit" value="Bestätigen">
</form>