<h1>Kurs anlegen</h1>

<?php

    if ($message == 'erfolgt'){
        echo "Daten konnten erfolgreich gespeichert werden. <br> 
              Sie werden auf die Home-Seite weiterverbunden. <br>";
        header("refresh:4; url = /user/home");
    }
    elseif ($error == 'falsedate'){
        echo "Kursende wurde vor dem Kursbeginn erfasst! <br>";
    }elseif ($error == 'nichterfolgt'){
    	echo "Daten konnten nicht gespeichert werden. <br>";
    }
		
?>
<br>

<?php /* 
<form action="anlegen" method="POST">
    <table>
        <tr><td> Kursname:</td>
            <td><input name='kursname' size="40" maxlength="250" type='text' required></td></tr>
        <tr><td> Kursstart:</td>
            <td><input name='kursstart' size="40" maxlength="250" type='date' required></td></tr>
        <tr><td> Kursende:</td>
            <td><input name='kursende' size="40" maxlength="250" type='date' required></td></tr>
        <tr><td> Sichtbarkeit:</td>
            <td><select name="sichtbarkeit">
			<option value= 1 >sichtbar</option>
			<option value= 0 selected>nicht sichtbar</option>
                </select></td></tr>
        <tr><td> Beschreibung:</td>
            <td><input name='beschreibung' type='text' required></td></tr>
    </table><br><br>
    <input type = "submit" value="Bestätigen">
</form>
<br><br>
 * 
 */
?>
<form>
    <div class="form-group">
        <label for="kursname"> Kursname </label>
        <input type="text" class="form-control" placeholder="Musterkurs" required>
    </div>
    <div class="form-group">
        <label for="kursstart"> Kursstart </label>
        <input type="date" class="form-control" placeholder="JJJ-MM-TT" required>
    </div>
    <div class="form-group">
        <label for="kursende"> Kursende </label>
        <input type="date" class="form-control" placeholder="JJJ-MM-TT" required>
    </div>
    <div class="form-group">
        <label for="sichtbarkeit"> Sichtbarkeit </label>
        <select name="sichtbarkeit">
			<option value= 1 >sichtbar</option>
			<option value= 0 selected>nicht sichtbar</option>
        </select>
    </div>
    <div class="form-group">
        <label for="beschreibung"> Beschreibung </label>
        <input type="text" class="form-control" placeholder="Kursbeschreibung" required>
    </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>