<h1>Kursangaben &auml;ndern</h1>

<?php 
    
use Zertifizierungstool\Model\Kurs;


if($error != "leer") { ?>
	
    <h5> Passen Sie die Kursdaten entsprechend an.</h5>

    <form method="post" action="changedata">
    <table>
        <tr><td>Kursname:</td><td> <input type="text" name="kursname" required value='<?php echo $result[1]?>'></td></tr>
        <tr><td>Kursstart:</td><td> <input type="date" name="kursstart" required value='<?php echo $result[2]?>'></td></tr>
        <tr><td>Kursende:</td><td> <input type="date" name="kursende" required value='<?php echo $result[3]?>'></td></tr>
        <tr><td>Sichtbarkeit:</td><td> 
                <select name="sichtbarkeit">
                    <?php
                        if($result[4] == 1){ ?>
                            <option value = 1 selected> sichtbar </option>
                        <?php } else { ?>
                            <option value= 0 selected>nicht sichtbar</option>
                        <?php } ?>
                </select>'></td></tr>
        <tr><td>Benutzername:</td><td> <input type="text" name="benutzername" required value='<?php echo $result[5]?>'></td></tr>
    </table>
    <br><br>
    <input type = "submit" value="Kursdaten ändern!"> 
    </form>

<?php }?>
?>

