<h1>Kurs anlegen</h1>

<?php

use Zertifizierungstool\Model\User;

if ($message == 'erfolgt'){
    ?>
    <div class="alert alert-success" role="alert">
        <p> Kurs wurde <strong>erfolgreich</strong> angelegt. Sie werden zu Ihren Kursen weitergeleitet </p>
    </div>
    <?php
   /* echo "<b><font color='green'>Kurs wurde erfolgreich angelegt!</font><br><br> 
          Sie werden zu Ihren Kursen weitergeleitet</b> <br>";
    */
    header("refresh:2; url = /kurs/showkurse");
}elseif ($error == 'falsedate'){
    ?>
    <div class="alert alert-danger" role="alert">
        <strong>Fehler!</strong> Kursende wurde vor dem Kursbeginn erfasst.
    </div>
    <?php 
}elseif ($error == '4days'){
    	?>
        <div class="alert alert-danger" role="alert">
            <strong>Fehler!</strong> Ein Kurs muss mindestens 4 Tage dauern.
        </div>
    <?php
}elseif ($error == 'nichterfolgt'){
    ?>
    <div class="alert alert-danger" role="alert">
        <strong>Fehler!</strong> Daten konnten nicht gespeichert werden.
    </div>
    <?php
}elseif ($error == 'endbeforecurrent'){
    ?>
    <div class="alert alert-danger" role="alert">
        <strong>Fehler!</strong> Kursende vor dem aktuellem Datum erfasst.
    </div>
    <?php
}
		
?>

<br>
<form action="create" method="POST">
    <div class="form-group">
        <label for="kursname"> Kursname </label>
        <input name="kursname" type="text" class="form-control" placeholder="Musterkurs" value="<?php echo $kurs->getKurs_name();?>" required>
    </div>
    <div class="form-group">
        <label for="kursstart"> Kursstart </label>
        <input name="kursstart" type="date" class="form-control" value="<?php echo $kurs->getKurs_start();?>" placeholder="JJJJ-MM-TT" required>
    </div>
    <div class="form-group">
        <label for="kursende"> Kursende </label>
        <input name="kursende" type="date" class="form-control" value="<?php echo $kurs->getKurs_ende();?>" placeholder="JJJJ-MM-TT" required>
    </div>
    
    <?php if($kurs->getSichtbarkeit() == 1) { ?>
            <div class="form-group">
                <label for="sichtbarkeit"> Sichtbarkeit </label>
                <select name="sichtbarkeit" class="form-control">
                                <option value= 1 selected>sichtbar</option>
                                <option value= 0 >nicht sichtbar</option>
                </select>
            </div>
        <?php }elseif($kurs->getSichtbarkeit() == 0) { ?>
            <div class="form-group">
                <label for="sichtbarkeit"> Sichtbarkeit </label>
                <select name="sichtbarkeit" class="form-control">
                                <option value= 1 >sichtbar</option>
                                <option value= 0 selected>nicht sichtbar</option>
                </select>
            </div>
        <?php }else { ?>
            <div class="form-group">
                    <label for="sichtbarkeit"> Sichtbarkeit </label>
                    <select name="sichtbarkeit" class="form-control">
                                <option value= 1 >sichtbar</option>
                                <option value= 0 selected>nicht sichtbar</option>
                    </select>
            </div>
    <?php } ?>
    
    
    <div class="form-group">
        <label for="beschreibung"> Beschreibung </label>
        <textarea style="resize:vertical" name="beschreibung" class="form-control" placeholder="Kursbeschreibung" required><?php echo $kurs->getBeschreibung();?></textarea>
    </div>
  <button type="submit" class="btn btn-default">Kurs anlegen</button>
</form>