<h1>Kurs anlegen</h1>

<?php

use Zertifizierungstool\Model\User;

//Nur eingeloggte Benutzer hab auf diese Seite Zugriff
if (User::currentUser()->istZertifizierer() || User::currentUser()->istAdmin()) {
    //mach nix
} else {
    header("Location: /user/home");
    exit();
}

if ($message == 'erfolgt'){
    echo "<b><font color='green'>Kurs wurde erfolgreich angelegt!</font><br><br> 
          Sie werden zu Ihren Kursen weitergeleitet</b> <br>";
    header("refresh:2; url = /kurs/showkurse");
}elseif ($error == 'falsedate'){
    echo "<b><font color ='red'>Kursende wurde vor dem Kursbeginn erfasst.</font></b> <br>";
}elseif ($error == 'nichterfolgt'){
    echo "<b><font color ='red'>Daten konnten nicht gespeichert werden.</font></b> <br>";
}elseif ($error == 'endbeforecurrent'){
    ?>
    <div class="alert alert-danger" role="alert">
        <strong>Fehler!</strong> Kursende vor dem aktuellem Datum erfasst.
    </div>
    <?php
}
		
?>
<br>
<form action="create" method="POST">
    <div class="form-group">
        <label for="kursname"> Kursname </label>
        <input name="kursname" type="text" class="form-control" placeholder="Musterkurs" required>
    </div>
    <div class="form-group">
        <label for="kursstart"> Kursstart </label>
        <input name="kursstart" type="date" class="form-control" placeholder="JJJJ-MM-TT" required>
    </div>
    <div class="form-group">
        <label for="kursende"> Kursende </label>
        <input name="kursende" type="date" class="form-control" placeholder="JJJJ-MM-TT" required>
    </div>
    <div class="form-group">
        <label for="sichtbarkeit"> Sichtbarkeit </label>
        <select name="sichtbarkeit" class="form-control">
			<option value= 1 >sichtbar</option>
			<option value= 0 selected>nicht sichtbar</option>
        </select>
    </div>
    <div class="form-group">
        <label for="beschreibung"> Beschreibung </label>
        <textarea style="resize:vertical" name="beschreibung" class="form-control" placeholder="Kursbeschreibung" required></textarea>
    </div>
  <button type="submit" class="btn btn-default">Kurs anlegen</button>
</form>