<h1>CSV-Einladung</h1>


<form method="post" action="csvinvite" enctype="multipart/form-data">


CSV-Datei ausw&auml;hlen: <input type="file" name="datei" required> <br><br>

<input type="submit" value="Datei jetzt ausw&auml;hlen">


</form>

<br><br>

<?php 

if($meldung=="datentyp") {
	echo "<b>Es sind nur CSV-Dateien erlaubt!</b>";
}

if($meldung=="dateigroesse") {
	echo "<b>Dateigr&ouml;sse von 2 MB darf nicht &uuml;berschritten werden!</b>";
}

if($meldung=="erfolgreich") {
	echo "<b><font color = 'green'>Upload der Datei war erfolgreich!</font></b>";
	
	
	echo "E-Mail-Adressen: <br>";
	
	$i=0;
	foreach($array as $a) {
		
		echo $a[$i];
		$i++;
		echo "<br>";
	}
	
	
}
?>
