<h1>Document manager</h1>

<br><br>

<?php 
use Zertifizierungstool\Model\Kurs;
	
	if($message == "Document deleted") { ?>
                <div class="alert alert-success" role="alert">
                    <p> Datei konnte <strong>erfolgreich</strong> gelöscht werden.<p>
                </div>
                <?php
		$_SESSION['foo'] = 'delete';
		header("refresh:2; url = /kurs/showdocuments");
        }elseif($message == 'Error deleting') { ?>
                <div class="alert alert-danger" role="alert">
                    <p> Datei konnte <strong>nicht</strong> gelöscht werden.<p>
                </div>
                <?php
		header("refresh:2; url = /kurs/showdocuments");
        }elseif($message == 'Access denied') { ?>
                <div class="alert alert-danger" role="alert">
                    <p> Sie haben <strong>nicht</strong> die <strong>erforderlichen Berechtigungen</strong> zum Ausführen dieser Seite.<p>
                </div>
                <?php
		header("refresh:2; url = /kurs/showdocuments");
        }
 ?>