<h1>Kurseinladung</h1>


<?php 

if($meldung=="erfolgreich"){
	
	echo "<b><font color='green'>Sie wurden erfolgreich in den Kurs eingetragen!</font></b>";
	
	
	header("refresh:2; url= /kurs/kursview?kurs_id=".$_SESSION['kurs']);
}

if($meldung=="falseuser"){
	
	echo "<b><font color='red'>Falscher Account!! Bitte loggen Sie sich aus und klicken Sie erneut auf den erhaltenen Link!";
}

if($meldung=="datenbankfehler"){

	echo "<b><font color='red'>Daten konnten aufgrund eines Datenbankfehlers nicht eingetragen werden! Bitte versuchen Sie es erneut!";
}

if($meldung=="alreadyexists"){

	echo "<b><font color='red'>Sie sind bereits im Kurs eingetragen!";
}

if($meldung=="dateerror") {
	
	echo "<b><font color='red'>Kurs ist bereits abgelaufen!";
	header("refresh:2; url = /kurs/showkurse");
}

if($meldung=="datefuture") {

	echo "<b><font color='red'>Kurs startet in der Zukunft!";
	header("refresh:2; url = /kurs/showkurse");
}


?>