<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Ihre Kurse: </h3>
            <table class="table table-hover">
        
        <tr>
        	<th> KursID </th>
			<th colspan="3"> KursName </th>
		</tr>
		
		<?php 
			foreach($result as $row){ ?>
			<tr>
				<td><?=$row['kurs_id']?></td>
				<td><?=$row['kurs_name']?></td>
				<td> <form accept-charset="utf-8" method="POST" action="changedata">
						<input type="hidden" value="<?=$row['kurs_id']?>"name="kurs_id">
						<input size="70" maxlength="250" value="ändern" type="submit">
					</form> </td>

			</tr>
		<?php }?>
		
		</table>

    </div>
</body>

