<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    use Zertifizierungstool\Model\Benutzer_Kurs;
    
    if (isset($status)) {
    	echo $status;
    }
    else{
?>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    <div class="container">
    	<h3>Kurs </h3>
    	
        <table class="table table-hover">
    	<tr><td>Kursname:</td><td> 	<?=$kurs->getKurs_name()?>		</td></tr>
        <tr><td>Kursstart:</td><td> <?=$kurs->getKurs_start()?>	</td></tr>
        <tr><td>Kursende:</td><td>	<?=$kurs->getKurs_ende()?>		</td></tr>
        <tr><td>Sichtbarkeit:</td>
        	<td> 
                     <?php
                        if($kurs->getSichtbarkeit() == 1)   	echo "öffentlich";
                      	else              						echo "privat";
                     ?> 
           </td>
       	</tr>
        <tr><td>Benutzername:</td><td><?=$kurs->getBenutzername()?></td></tr>
        <tr><td>Teilnehmeranzahl:</td><td><?=$kurs->getTeilnehmerzahl()?></td></tr>
        <tr><td>Beschreibung:</td><td><?=$kurs->getBeschreibung()?></td></tr>
        </table>
        
		<?php  }    ?>
        
                <form accept-charset="utf-8" method="POST" action="showdocuments">
                    <input type="hidden" value="<?=$kurs->getKurs_id()?>" name="kurs_id">
                    <input type="hidden" value="<?=$kurs->getKurs_name()?>" name="kurs_name">
                    <input size="70" maxlength="250" value="Kursdokumente anzeigen" type="submit">
                </form> <br>
                
                <?php 
                    // Prüfen, ob Teilnehmer für den Kurs schon eingetragen ist
                    // Wenn Benutzer im Kurs eingetragen ist, dann kann er austreten
                    if(User::currentUser()->istTeilnehmer() && $benutzer_kurs->alreadyexist(User::currentUser()->getBenutzername(), $kurs->getKurs_id())) {
                        ?>
                        <form accept-charset="utf-8" method="POST" action="signoutkurs">
                            <input type="hidden" value="<?=$kurs->getKurs_id()?>" name="kurs_id">
                            <input size="70" maxlength="250" value="Aus Veranstaltung austragen" type="submit">
                        </form> <br>
                        <?php
                    }
                    
                    if(User::currentUser()->istTeilnehmer() && !$benutzer_kurs->alreadyexist(User::currentUser()->getBenutzername(), $kurs->getKurs_id())) {
                    	?>
                                            <form accept-charset="utf-8" method="POST" action="enterkurs">
                                                <input type="hidden" value="<?=$kurs->getKurs_id()?>" name="kurs_id">
                                                <input type="hidden" name="enterpubliccourse">
                                                <input size="70" maxlength="250" value="Kurs beitreten" type="submit">
                                            </form> <br>
                                            <?php
                                        }
                    ?>
                
                <?php 
                if(User::currentUser()->istAdmin() || User::currentUser()->istZertifizierer()) { ?>
                
                    <form accept-charset="utf-8" method="POST" action="upload">
                        <input type="hidden" value="<?php echo $kurs->getKurs_id();?>" name="kurs_id">
                        <input size="70" maxlength="250" value="Datei hinzufügen" type="submit">
                    </form> <br>

                    <!--  author Michael Zillner -->


					<?php 
					
					//$kurs = new Kurs();
					
					if($kurs->active($_SESSION['kurs_id'])) {
					
					?>


                    <form accept-charset="utf-8" method="POST" action="csvinvite">
                        <input type="hidden" value="<?php echo $kurs->getKurs_id();?>" name="kurs_id">
                        <input size="70" maxlength="250" value="Teilnehmer &uuml;ber CSV einladen" type="submit">
                    </form> <br>

                    <form accept-charset="utf-8" method="POST" action="singleinvite">
                           <input type="hidden" value="<?php echo $kurs->getKurs_id();?>" name="kurs_id">
                       <input size="70" maxlength="250" value="Einzelnen Teilnehmer einladen" type="submit">
                    </form>
                    <br><br>
                    
                    <form method="post" action="pdf">
					<input type="hidden" value="pdf" name='pdf'>
					<input type="submit" value="Zertifikat herunterladen!">
					</form>
					
					 <br><br>
					
                    <a href="<?= $this->url('pruefung', ['action' => 'overview', 'id' => $kurs->getKurs_id()])?>"><button type="button">Zu den Pr&uuml;fungen</button></a>
                <?php }} ?>
                        
    </div>
    </body>
    
    