
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    use Zertifizierungstool\Model\Benutzer_Kurs;
    
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h1>Ihre Kurse: </h1><br>
            <table class="table table-hover">
        
        <tr>
        	<th> KursName </th>
		<th> KursStart </th>
                <th> KursEnde </th>
                <th> KursLeiter </th>
                <th> anzeigen </th>
                <th> austragen </th>
	</tr>
		
		<?php 
			foreach($result as $r){ 
		        $user = new User();
		        $load_user = $user->load($r->getBenutzername());
		        ?>
			<tr>
				<td><?=$r->getKurs_name()?></td>
				<td><?=$r->getKurs_start()?></td>
				<td><?=$r->getKurs_ende()?></td>
                                <td><?php echo ($user->getVorname()); echo" "; echo ($user->getNachname());?></td>
                                <td> <form accept-charset="utf-8" method="POST" action="kursview">
                                        <input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
                                        <button type="submit" class="btn btn-info">
                                                    <span class="glyphicon glyphicon-eye-open"></span>
                                        </button>
                                </form> </td>
                                <td>
                                    <form accept-charset="utf-8" method="POST" action="checksignoutkurs">
                                        <input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
                                        <input type="hidden" value="showsignedkurse" name="site">
                                        <button type="submit" class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-remove"></span>
                                        </button>
                                    </form>
                                </td>
			</tr>
                        <?php }?>
		
            </table>

    </div>
    
    	
</body>

