<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Aktuell verf&uuml;gbare Kurse: </h3>
            <table class="table table-hover">
                <tr>
                        <th> KursID </th>
                        <th> KursName </th>
                        <th> Kursstart </th>
                        <th> Kursende </th>
                </tr>
		
		<?php
			foreach($result as $r){ ?>
			<tr>
				<td><?=$r->getKurs_id()?></td>
				<td><?=$r->getKurs_name()?></td>
				<td><?=$r->getKurs_start()?></td>
				<td><?=$r->getKurs_ende()?></td>
                                
                                <?php 
                                if(User::currentUser()->istAdmin() || User::currentUser()->istZertifizierer()) { ?>
				<td> <form accept-charset="utf-8" method="POST" action="changedata">
						<input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
						<input size="70" maxlength="250" value="ändern" type="submit">
                                     </form> 
                                </td>
                                <?php } ?>
					
                                <td> <form accept-charset="utf-8" method="POST" action="kursview">
						<input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
						<input size="70" maxlength="250" value="anzeigen" type="submit">
                                     </form> 
                                </td>
			
			</tr>
                        <?php }?>
		
            </table>

    </div>
</body>

