<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    use Zertifizierungstool\Model\Benutzer_Kurs;
    
    //Nur eingeloggte Benutzer hab auf diese Seite Zugriff
    if (!User::currentUser()->istZertifizierer() || !User::currentUser()->istAdmin() || !User::currentUser()->istTeilnehmer()) {
        header("Location: /user/home");
        exit();
    }
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Ihre Kurse: </h3>
            <table class="table table-hover">
        
        <tr>
        	<th> KursName </th>
		<th> KursStart </th>
                <th> KursEnde </th>
                <th> KursLeiter </th>
                <th></th>
                <th></th>
		</tr>
		
		<?php 
			foreach($result as $row){ ?>
			<tr>
				<td><?=$row['kurs_name']?></td>
				<td><?=$row['kurs_start']?></td>
                                <td><?=$row['kurs_ende']?></td>
                                <td><?=$row['benutzername']?></td>					
                                <td> <form accept-charset="utf-8" method="POST" action="kursview">
                                        <input type="hidden" value="<?=$row['kurs_id']?>"name="kurs_id">
                                        <input size="70" maxlength="250" value="anzeigen" type="submit">
                                </form> </td>
                                <td>
                                    <form accept-charset="utf-8" method="POST" action="signoutkurs">
                                        <input type="hidden" value="<?=$row['kurs_id']?>" name="kurs_id">
                                        <input size="70" maxlength="250" value="Aus Veranstaltung austragen" type="submit">
                                    </form>
                                </td>
			</tr>
                        <?php }?>
		
            </table>

    </div>
    
    	 <br>
   					<form method="post" action="pdf">
					<input type="hidden" value="pdflist" name='pdflist'>
					<input type="submit" value="Meine Zertifikate anzeigen">
					</form>
					
					 <br>
</body>

