<form method="post" action="kursview">
<input type="submit" value="zur&uuml;ck zur Kurs&uuml;bersicht" name="back">
<input type="hidden" value="<?php echo $_SESSION['kurs_id']; ?>" name='kurs_id'>
</form>
<br>
<h1>Kursdokumente</h1>

<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    
    //Nur eingeloggte Benutzer hab auf diese Seite Zugriff
    if (User::currentUser()->istZertifizierer() || User::currentUser()->istAdmin() || User::currentUser()->istTeilnehmer()) {
        //mach nix
    } else {
        header("Location: /user/home");
        exit();
    }
    
    if (isset($status)) {
        echo $status;
    }
    else{
   
?>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


 
    <div class="container">
    	<h3>Dokumente zum Kurs <?php echo $kursname;?>: </h3>
            <table class="table table-hover">
                <tr><th>Dateinname</th><th>Dateiformat</th><th>Dateigröße</th><th>Aktion</th></tr>
                
                   
                        <?php
                            foreach($alldocuments as $document){
                     
                                //Dokumentinformationen auslesen
                                $documentdetail = pathinfo($path."/".$document);
                                ?>
              	<tr>            
                    <td>
                                <a href="<?php echo realpath($documentdetail['dirname']."/".$documentdetail['basename']);?>"><?php echo $documentdetail['filename']; ?></a>
                            
                    </td>
                    <td>
                        	<?php 
                                echo $documentdetail['extension'];                   
                       		?>
                    </td>
                    <td>
                        <?php
                               //Größe ermitteln in kbyte, indem durch 1024 geteilt und gerundet wird
                                $size = ceil(filesize($path."/".$document)/1024);
                                echo $size;
                        ?>
                    </td>
                    
                    <?php  if(User::currentUser()->istAdmin() || User::currentUser()->istZertifizierer()) {?>
                    <td>
                    			<form accept-charset="utf-8" method="POST" action="docDelete">
                    			<input type="hidden" value="<?=$document	?>"name="document"> 
                    			<input type="hidden" value="<?=$path	?>"name="path">
                    			<input type="hidden" value="thissite" name='thissite'>
                    			<input size="70" maxlength="250" value="L&oumlschen" type="submit">
                    			</form>
                    </td>
                    	<?php }
                    	else
                    	?>
                    	 <td>
                    			<form accept-charset="utf-8" method="POST" action="docdownload">
                    			<input type="hidden" value="<?=$document					?>"name="document"> 
                    			<input type="hidden" value="<?=$path						?>"name="path">
                    			<input type="hidden" value="<?=$documentdetail['extension']	?>"name="extension">
                    			<input type="hidden" value="download" name='download'>
                    			<input size="70" maxlength="250" value="Herunterladen" type="submit">
                    			</form>
                    </td>
                    	
             	</tr>
                    	<?php                     					
                    			}
                    	?>
                    
                
            </table>
    </div>
</body>

<?php } ?>