<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Archivierte Kurse: </h3>
            <table class="table table-hover">
        
        <tr>
        	<th> KursID </th>
		<th> KursName </th>
                <th> KursStart </th>
                <th> KursEnde </th>
                <th></th>
                <th></th>
	</tr>
		
		<?php
			foreach($result as $r){ ?>
			<tr>
				<td><?=$r->getKurs_id()?></td>
				<td><?=$r->getKurs_name()?></td>
                                <td><?=$r->getKurs_start()?></td>
                                <td><?=$r->getKurs_ende()?></td>
					
                                <td><form accept-charset="utf-8" method="POST" action="kursview">
						<input type="hidden" value="<?=$r->getKurs_id()?>"name="kurs_id">
						<input size="70" maxlength="250" value="anzeigen" type="submit">
                                    </form> </td>
                                
                                 
				<td><form accept-charset="utf-8" method="POST" action="changedata">
						<input type="hidden" value="<?=$r->getKurs_id()?>"name="kurs_id">
                                                <input type="hidden" value=1 name="archiv">
						<input size="70" maxlength="250" value="Kursdaten kopieren" type="submit">
                                    </form> </td>
			</tr>
		<?php }?>
		
            </table>

    </div>
</body>

