<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Archivierte Kurse: </h3>
            <div style= "height:500px; overflow-y:scroll">
            <table class="table table-hover">
        
            <tr>
        	<th> KursID </th>
		<th> KursName </th>
                <th> KursStart </th>
                <th> KursEnde </th>
                <th> anzeigen</th>
                <th> Kursdaten kopieren</th>
            </tr>
		
		<?php
			foreach($result as $r){ ?>
			<tr>
				<td><?=$r->getKurs_id()?></td>
				<td><?=$r->getKurs_name()?></td>
                                <td><?=$r->getKurs_start()?></td>
                                <td><?=$r->getKurs_ende()?></td>
                                <td><form accept-charset="utf-8" method="POST" action="kursview">
						<input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
						<button type="submit" class="btn btn-info">
                                                        <span class="glyphicon glyphicon-eye-open"></span>
                                                </button>
                                    </form> 
                                </td>
                                
                                 
				<td><form accept-charset="utf-8" method="POST" action="changedata">
						<input type="hidden" value="<?=$r->getKurs_id()?>"name="kurs_id">
                                                <input type="hidden" value=1 name="archiv">
						<button type="submit" class="btn btn-warning">
                                                        <span class="glyphicon glyphicon-duplicate"></span>
                                                </button> 
                                    </form> 
                                </td>
			</tr>
		<?php }?>
		
            </table>
            </div>
    </div>
</body>

