<?php

use Zertifizierungstool\Model\Pruefung;
?>


<h1> Kursstatistik </h1>
<h3> alle Pr&uuml;fungen:</h3>


<table>
<tr><th>Pr&uuml;fung</th><th>Anzahl der Pr&uuml;flinge</th><th>Bestehensquote</th></tr>
<?php 

if (isset($pruefungsliste_empty)) {
	foreach($pruefungsliste_empty as $p) {
		?>
		
	<tr><td><?php echo $p->getName();?></td><td>0</td><td>0</td></tr>
	
<?php }
} else {

foreach($pruefungsliste as $p) {
	?>
	
<tr><td><?php echo $p->getName();?></td><td><?php echo $p->getAnzahlMitgeschrieben(); ?></td><td><?php echo $p->getBestehensquote();?></td></tr>

<?php }}?>


</table>