<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    use Zertifizierungstool\Model\Benutzer_Kurs;
    
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Ihre Kurse: </h3><br>
            <table class="table table-hover">
        
        <tr>
        	<th> KursName </th>
		<th> KursStart </th>
                <th> KursEnde </th>
                <th> KursLeiter </th>
                <th></th>
                <th></th>
		</tr>
		
		<?php 
			foreach($result as $r){ 
		        $user = new User();
		        $load_user = $user->load($r->getBenutzername());
		        ?>
			<tr>
				<td><?=$r->getKurs_name()?></td>
				<td><?=$r->getKurs_start()?></td>
				<td><?=$r->getKurs_ende()?></td>
                                <td><?php echo ($user->getVorname()); echo" "; echo ($user->getNachname());?></td>
                                <td> <form accept-charset="utf-8" method="POST" action="kursview">
                                        <input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
                                        <input size="70" maxlength="250" value="anzeigen" class="btn btn-default" type="submit">
                                </form> </td>
                                <td>
                                    <form accept-charset="utf-8" method="POST" action="signoutkurs">
                                        <input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
                                        <input size="70" maxlength="250" value="Aus Veranstaltung austragen" class="btn btn-default" type="submit">
                                    </form>
                                </td>
			</tr>
                        <?php }?>
		
            </table>

    </div>
    
    	
</body>

