<h1>Kurs</h1>
<?php
    use Zertifizierungstool\Model\Kurs;
    use Zertifizierungstool\Model\User;
    use Zertifizierungstool\Model\Benutzer_Kurs;
    
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    
    <div class="container">
    	<h3>Aktuell verf&uuml;gbare Kurse: </h3><br>
            <div style= "height:600px; overflow-y:scroll">
            <table class="table table-hover">
                <tr>
                        <th> KursID </th>
                        <th> KursName </th>
                        <th> Kursstart </th>
                        <th> Kursende </th>
                        
                        <?php if (User::currentUser()->istTeilnehmer()) {?>
                        <th> Beigetreten </th>
                        <?php }?>
                        
                        <?php if(User::currentUser()->istAdmin() || User::currentUser()->istZertifizierer()) { ?>
                        <th> bearbeiten </th>
                        <?php }?>
                        
                        <th> anzeigen </th>
                </tr>
		
		<?php
			foreach($result as $r){ ?>
			<tr>
				<td><?=$r->getKurs_id()?></td>
				<td><?=$r->getKurs_name()?></td>
				<td><?=$r->getKurs_start()?></td>
				<td><?=$r->getKurs_ende()?></td>
				
				               				<?php 
				          if (User::currentUser()->istTeilnehmer()){
								$benutzer_kurs = new Benutzer_Kurs();
								if ($benutzer_kurs->alreadyexist(User::currentUser()->getBenutzername(), $r->getKurs_id())) {?>
                                
                        			  <td align="center"><span class="glyphicon glyphicon-ok"></span></td>      
                                
                                <?php } else { ?>
                                
                                <td> </td>
                                
                                <?php }}?>

                                
                                <?php 
                                $kurs = new Kurs();
                                if(User::currentUser()->istAdmin() || User::currentUser()->istZertifizierer()) {//$kurs->istKursleiter(User::currentUser()->getBenutzername(), $kurs->getKurs_id())) { ?>
				<td> <form accept-charset="utf-8" method="POST" action="changedata">
						<input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
                                                <button type="submit" class="btn btn-warning">
                                                        <span class="glyphicon glyphicon-edit"></span>
                                                </button>  
                                     </form> 
                                </td>
                                <?php } ?>
					
                                <td> <form accept-charset="utf-8" method="POST" action="kursview">
						<input type="hidden" value="<?=$r->getKurs_id()?>" name="kurs_id">
						<button type="submit" class="btn btn-info">
                                                        <span class="glyphicon glyphicon-eye-open"></span>
                                                </button> 
                                     </form> 
                                </td>
               

			
			</tr>
                        <?php }?>
				
            </table>
            </div>
    </div>
</body>

