<h1>Kurs</h1>

<?php
if($meldung == "erfolgreich") {
    ?>
    <div class="alert alert-success" role="alert">
        <p> Sie konnten sich erfolgreich aus dem Kurs austragen. </p>
    </div>
    <?php
    //echo "<b><font color ='green'>Sie konnten sich erfolgreich aus dem Kurs austragen.</font></b>";
    header("refresh:2; url = /kurs/showsignedkurse");
} 
if($meldung == "fehlerhaft") {
    ?>
    <div class="alert alert-error" role="alert">
        <p> Beim Austragen trat ein Fehler auf, versuchen Sie es bitte erneut! </p>
    </div>
    <?php
    //echo "Beim Austragen trat ein Fehler auf, versuchen Sie es bitte erneut!";
	header("refresh:2; url=/kurs/showsignedkurse");
    ?>
    <br><br>
    <form method="post" action="showkurse">
        <input type="submit" value="zur&uuml;ck zur Kurs&uuml;bersicht" name="back">
        <input type="hidden" value="<?php echo $_SESSION['kurs_id']; ?>" name='kurs_id'>
    </form>
    <br>
    <?php
} 


?>
