<h1>Kurs</h1>

<?php
if($meldung == "erfolgreich") {
    echo "Sie konnten sich erfolgreich aus dem Kurs austragen.";
    header("refresh:4; url = /user/home");
} 
if($meldung == "fehlerhaft") {
    echo "Beim Austragen trat ein Fehler auf, versuchen Sie es bitte erneut!";
    ?>
    <br><br>
    <form method="post" action="showkurse">
        <input type="submit" value="zur&uuml;ck zur Kurs&uuml;bersicht" name="back">
        <input type="hidden" value="<?php echo $_SESSION['kurs_id']; ?>" name='kurs_id'>
    </form>
    <br>
    <?php
} 


?>
