<h1>Einzelnen Teilnehmer einladen</h1>


<form Method="post" Action="singleinvite">
<table>

<tr><td width="150">E-Mail Adresse:</td><td><input type="email" size="25" name="email" required></td></tr>

</table>
<input type="hidden" value="singleinvite" name='site'>
<input type="submit" value="Jetzt einladen">
</form>



<?php if (isset($erfolgreich)) {

	echo "E-Mail wurde erfolgreich an <b>".$erfolgreich."</b> versandt.";
	
}?>

<?php if (isset($fehler)) {

	echo "Es liegt bereits eine Einladung für die E-Mail Adresse <b>".$fehler."</b> vor.";
	
}?>

<br><br>
<form method="post" action="kursview">
<input type="submit" value="zur&uuml;ck zur Kurs&uuml;bersicht">


</form>