<h1>Einzelnen Teilnehmer einladen</h1>


<form Method="post" Action="singleinvite">
<table>

<tr><td width="150">E-Mail Adresse:</td><td><input type="email" size="35" name="email" required></td></tr>

</table>
<input type="hidden" value="singleinvite" name='site'>
<input type="submit" class="btn btn-default" value="Jetzt einladen">
</form>
<br><br>


<?php if (isset($erfolgreich)) {

	echo "E-Mail wurde erfolgreich an <b>".$erfolgreich."</b> versandt.";
	
}?>

<?php if (isset($fehler)) {

	echo "Es liegt bereits eine Einladung f&uuml;r die E-Mail Adresse <b>".$fehler."</b> vor.";
	
}?>

<br><br>
<form method="post" action="kursview">
<input type="submit" class="btn btn-default" value="zur&uuml;ck zur Kurs&uuml;bersicht">
<input type="hidden" value="<?php echo $_SESSION['kurs_id']; ?>" name='kurs_id'>

</form>