<h1>Kursstatistik</h1>
<h3>Einzelnen Fragen zur Prüfung <?php echo $pruefung_name?></h3>
<table class="table table-hover">
<thead>
<tr><th width = "40%"><font size="3">Frage</font></th><th width = "20%"><font size="3">gesamt beantwortet</font></th><th width = "20%"><font size="3">davon richtig</font></th><th width = "20%"><font size="3">richtig in %</font></th></tr>
</thead>

<tbody>
<?php
foreach($ergebnis as $e){
	
	?>
	
	<tr><td><?php echo $e[0]?></td><td><?php echo $e[1]?></td><td><?php echo $e[2]?></td><td><?php echo $e[3]?></td></tr>
<?php 

}
?>



</tbody>

</table>