<h1> Kursmaterial hochladen</h1>



<form method="post" action="upload" enctype="multipart/form-data">
Dokument: <input type='file' name='datei' id='datei'><br>

<input type="hidden" value="thissite" name='thissite'> <br><br>
<input type='submit' class="btn btn-default" value='Upload ' name='submit'>
</form><br><br>
<?php 
if(isset($meldung)){
	if($meldung=='datentyp') echo "<b>Datentyp ist falsch!</b>";
	elseif($meldung=='dateigroesse') echo "<b>Datei ist zu gross!</b>";
	elseif($meldung=='erfolgreich') echo"<b>Datei wurde erfolgreich hochgeladen!</b>";
	
}
	
		
?>
<form method="post" action="kursview">
<input type="submit" class="btn btn-default" value="zur&uuml;ck zur Kurs&uuml;bersicht" name="back">
<input type="hidden" value="<?php echo $_SESSION['kurs_id']; ?>" name='kurs_id'>

</form>
