<?php use Zertifizierungstool\Model\User; ?>

<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Zertifizierungstool')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
		?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        
       
        
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown"><a href="<?= $this->url('home') ?>"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                        
                        <?php 
                        	if (User::currentUser()->istAdmin()) { ?>
                        		<li class="dropdown"><a href="http://132.231.36.205/user/register"><span class="glyphicon glyphicon-user"></span> Benutzer anlegen</a></li>
                                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-education"></span> Kursverwaltung </a>
          					        <ul class="dropdown-menu">
                                                               	<li><a href="http://132.231.36.205/kurs/showkurse"> Übersicht aktueller Kurse </a></li>
                                                                <li><a href="http://132.231.36.205/kurs/showarchivedkurse"> Übersicht archivierte Kurse </a></li>
                                                                <li><a href="http://132.231.36.205/kurs/showsignedkurse">eingeschrieben</a></li>
                                                                <li><a href="http://132.231.36.205/kurs/showcreatedkurse">angelegte Kurse</a></li>
                                                                <li><a href="http://132.231.36.205/kurs/create"> neuen Kurs anlegen </a></li>
        						</ul>
        						</li>
        						<li class="dropdown"><a href="http://132.231.36.205/kurs/loadcertificate?pdflist"><span class="glyphicon glyphicon-file"></span> Zertifikatsübersicht</a></li>
                        <?php	
                        	}elseif(User::currentUser()->istZertifizierer()) {  ?>
                        
                        		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-education"></span> Kursverwaltung </a>
          					        <ul class="dropdown-menu">
                                                                <li><a href="http://132.231.36.205/kurs/showkurse"> Übersicht aktueller Kurse </a></li>
                                                                <li><a href="http://132.231.36.205/kurs/showarchivedkurse"> Übersicht archivierte Kurse </a></li>
                                                                <li><a href="http://132.231.36.205/kurs/showcreatedkurse">angelegte Kurse</a></li>
                                                                <li><a href="http://132.231.36.205/kurs/create"> neuen Kurs anlegen </a></li>
        						</ul>
        				</li>
 
                        		
                        <?php	
                        	}elseif (User::currentUser()->istTeilnehmer()) { ?>
                        		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-education"></span> Kurse </a>
                        			<ul class="dropdown-menu">
                                                    <li><a href="http://132.231.36.205/kurs/showkurse">öffentliche Kurse</a></li>
                                                    <li><a href="http://132.231.36.205/kurs/showsignedkurse">Meine Kurse</a></li>
                                                </ul>
                                        </li>
                                        <li class="dropdown"><a href="http://132.231.36.205/kurs/loadcertificate?pdflist"><span class="glyphicon glyphicon-file"></span> Zertifikatsübersicht</a></li>
                                        
                        <?php	
                        	}else { ?>

                        <?php 		
                        	}
                        ?>
                       
                    </ul>
                     <ul class="nav navbar-nav navbar-right">
                     	<?php if (User::currentUser()->getBenutzername()==NULL) {?>
        					<li><a href="http://132.231.36.205/user/register"><span class="glyphicon glyphicon-user"></span> Registrieren</a></li>
        				<?php }else {?>
        					<li class="dropdown">
          					<a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo User::currentUser()->getBenutzername()." ";?><span class="glyphicon glyphicon-user"></span></a>
          					<ul class="dropdown-menu">
        						<li><a href="http://132.231.36.205/user/changedata">Benutzerdaten &auml;ndern</a></li>
        						<li><a href="http://132.231.36.205/user/changepassword">Passwort &auml;ndern</a></li>
        					</ul>
        					</li>
        				<?php }
        				if (User::currentUser()->getBenutzername()==NULL) { ?>
      				 	<li><a href="http://132.231.36.205/user/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      				 	<?php } else {?>
      				 	<li><a href="http://132.231.36.205/user/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      				 	<?php }?>
      				</ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
         
        
        <br><br>
        <div style="text-align:center; width:100%">
        
        Copyright &copy 2017 Zert4Tool | <a href="mailto:zert4tool@uni-passau.de">zert4tool@uni-passau.de</a> | <a href="http://132.231.36.205/impressum.phtml">Impressum</a>
        
       </div>
        </div>
        <?= $this->inlineScript() ?>
        
       
      
        
    </body>
</html>
