<?php use Zertifizierungstool\Model\User; 

echo User::currentUser()->getBenutzername();
echo User::currentUser()->istAdmin();?>

<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Zertifizierungstool')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
		?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        
                        <?php 
                        	if (User::currentUser()->istAdmin()) { ?>
                        		<li class="active"><a href="http://132.231.36.205/user/register">Benutzer anlegen</a></li>
                        		<li class="active"><a href="http://132.231.36.205/pruefung/create">Pruefung anlegen (voruebergehend)</a></li>
                        <?php	
                        	}elseif(User::currentUser()->istZertifizierer()) { ?>
                        		
                        <?php	
                        	}elseif (User::currentUser()->istTeilnehmer()) { ?>
                        		
                        <?php	
                        	}
                        ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
