<h1>Benutzerdaten &auml;ndern</h1>

<?php 
if($status == "erfolgreich") { ?>
	
<a>Benutzerdaten wurden erfolgreich ge&auml;ndert</a>

<?php 

header("refresh:2; url = /user/home");}

else {?>

<form method="post" action="changedata">
<table>
<tr><td>Vorname:</td><td> <input type="text" name="vorname" required value='<?php echo $benutzerdaten[1]?>'></td></tr>
<tr><td>Nachname:</td><td> <input type="text" name="nachname" required value='<?php echo $benutzerdaten[2]?>'></td></tr>
<tr><td>Geburtsdatum:</td><td> <input type="date" name="geburtsdatum" required value='<?php echo $benutzerdaten[3]?>'></td></tr>
<tr><td>Strasse:</td><td> <input type="text" name="strasse" required value='<?php echo $benutzerdaten[4]?>'></td></tr>
<tr><td>Postleitzahl:</td><td> <input type="text" name="plz" required value='<?php echo $benutzerdaten[5]?>'></td></tr>
<tr><td>Ort:</td><td> <input type="text" name="ort" required value='<?php echo $benutzerdaten[6]?>'></td></tr>
<tr><td>E-Mail:</td><td> <input type="email" name="email" required value='<?php echo $benutzerdaten[7]?>'></td></tr>

</table>
<br><br>
<input type = "submit" value="Benutzerdaten jetzt &auml;ndern!"> 
</form>

<?php 

if (isset($status)){

	echo "<b><font color=red>E-Mail-Adresse bereits vorhanden. Bitte andere Mailadresse benutzen!</b></font>";

}

}?>