<h1>Passwort &auml;ndern</h1>

<?php
$error = "";
if($status == "erfolgreich") { ?>
	
<a>Passwort wurde erfolgreich ge&auml;ndert</a>

<?php 

header("refresh:2; url = /user/home");}

else {?>

<form method="post" action="changepassword">
<table>
<tr><td>altes Passwort:</td><td> <input type="password" name="passwort" required></td></tr>
<tr><td>Neues Passwort:</td><td> <input type="password" name="passwort1" required></td></tr>
<tr><td>Neues Passwort best&auml;tigen:</td><td> <input type="password" name="passwort2" required></td></tr>


</table>
<br><br>
<input type = "submit" value="Passwort jetzt &auml;ndern!"> 
</form><br><br>

<?php 
	if ($status == 'datenbankfehler') {
		$error = "Daten konnten nicht erfasst werden. Bitte versuchen Sie es erneut!";
	
	}
	elseif ($stauts == 'ungleiche passwoerter') {
		$error = "Das best&auml;tigte Passwort stimmt nicht mit dem neuen Passwort &uuml;berein.";
	
	}
	elseif ($status == 'altes passwort falsch') {
		$error = "Das eigegebene Passwort ist falsch!";
	
	}

	echo $error;
}
?>