<h1>Passwort &auml;ndern</h1>
<br><br>

<?php

if($status == "erfolgreich") { ?>
	
<p style='color:green'><b>Passwort wurde erfolgreich ge&auml;ndert</b></p>

<?php 

header("refresh:2; url = /user/home");}

else {?>

<form class="form-horizontal" method="post" action="changepassword">

<div class="form-group">
	<label class="control-label col-sm-2"> altes Passwort</label>
	<div class="col-sm-3">
		<input type="password" class= "form-control" name="passwort" required>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> neues Passwort</label>
	<div class="col-sm-3">	
		<input type="password" class= "form-control" name="newPasswort1" required>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> neues Passwort best&auml;tigen</label>
	<div class="col-sm-3">	
		<input type="password" class= "form-control" name="newPasswort2" required>
	</div>
</div>

<br><br>
<input type = "submit" class="btn btn-default" value="Passwort jetzt &auml;ndern!"> 

</form>
<br><br><br>

<?php 
	if ($status == 'datenbankfehler') {
		$error = "Daten konnten nicht erfasst werden. Bitte versuchen Sie es erneut!";
	
	}
	elseif ($status == 'ungleiche passwoerter') {
		$error = "Das best&auml;tigte Passwort stimmt nicht mit dem neuen Passwort &uuml;berein.";
	
	}
	elseif ($status == 'altes passwort falsch') {
		$error = "Das eingegebene Passwort ist falsch!";
	
	}

	echo "<b><font color=red>".$error."</b></font>";
}
?>