<h1>Benutzerdaten &auml;ndern</h1>
<br><br>

<?php 
if($status == "erfolgreich") { ?>
	
<p style="color:green"><b> Benutzerdaten wurden erfolgreich ge&auml;ndert!</b></p>

<?php 

header("refresh:2; url = 132.231.36.205");}
//header("refresh:2; url = /user/home");}

else {?>

<form class="form-horizontal" method="post" action="changedata">

<div class="form-group">
	<label class="control-label col-sm-2"> Vorname</label>
	<div class="col-sm-5">
		<input type="text" class= "form-control" name="vorname" required value='<?php echo $benutzerdaten[1]?>'>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> Nachname</label>
	<div class="col-sm-5">
		<input type="text" class= "form-control" name="nachname" required value='<?php echo $benutzerdaten[2]?>'>
	</div>
</div>
<div class="form-group">	
	<label class="control-label col-sm-2"> Geburtsdatum</label>
	<div class="col-sm-5">
		<input type="date" class= "form-control" name="geburtsdatum" required value='<?php echo $benutzerdaten[3]?>'>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> Stra&szlig;e</label>
	<div class="col-sm-5">
		<input type="text" class= "form-control" name="strasse" required value='<?php echo $benutzerdaten[4]?>'>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> Postleitzahl</label>
	<div class="col-sm-5">
		<input type="text" class= "form-control" name="plz" required value='<?php echo $benutzerdaten[5]?>'>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> Ort</label>
	<div class="col-sm-5">
		<input type="text" class= "form-control" name="ort" required value='<?php echo $benutzerdaten[6]?>'>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-sm-2"> E-Mail</label>
	<div class="col-sm-5">
		<input type="email" class= "form-control" name="email" required value='<?php echo $benutzerdaten[7]?>'>
	</div>
</div>

<br><br>
<input type = "submit" class="btn btn-default" value="Benutzerdaten jetzt &auml;ndern!"> 
</form>
<br><br><br>

<?php 

if (isset($status)){

	echo "<b><font color=red>E-Mail-Adresse bereits vorhanden. Bitte andere Mailadresse benutzen!</b></font>";

}

}?>