
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    <div class="container"> 

<h2>Impressum</h2>
<p>Zert4Tool<br />
Innstra&szlig;e 41<br />94032 Passau</p>
<p>Telefon: +49851132580<br />
Telefax: +49851132581<br />
E-Mail: <a href="mailto:zert4tool@uni-passau.de">zert4tool@uni-passau.de</a><br />
</p>
<p><strong>Vertreten durch:</strong><br />Gesch&auml;ftsf&uuml;hrer Martin Waldmann</p><p><strong>Registereintrag:</strong><br />Eingetragen im Genossenschaftsregister.<br />Registergericht: Passau<br />Registernummer: DE213156464896</p><p><strong>Umsatzsteuer-ID: </strong><br />Umsatzsteuer-Identifikationsnummer nach &sect;27a Umsatzsteuergesetz:<br />213156464896</p><p><strong>Wirtschafts-ID: </strong>Wirtschafts-IdNr: 213156464895</p><strong>Aufsichtsbeh&ouml;rde: </strong>Uni Passau<br /><br /><h2>Hinweis auf EU-Streitschlichtung</h2>Zur au&szlig;ergerichtlichen Beilegung von verbraucherrechtlichen Streitigkeiten hat die Europ&auml;ische Union eine Online-Plattform (&quot;OS-Plattform&quot;) eingerichtet, an die Sie sich wenden k&ouml;nnen. Die Plattform finden Sie unter <a href="http://ec.europa.eu/consumers/odr/">http://ec.europa.eu/consumers/odr/</a>. Unsere Emailadresse lautet: zert4tool@uni-passau.de<br /><br /><br /><h2>Disclaimer &mdash; rechtliche Hinweise</h2>
&sect; 1 Warnhinweis zu Inhalten<br />
Die kostenlosen und frei zug&auml;nglichen Inhalte dieser Webseite wurden mit gr&ouml;&szlig;tm&ouml;glicher Sorgfalt erstellt. Der Anbieter dieser Webseite &uuml;bernimmt jedoch keine Gew&auml;hr f&uuml;r die Richtigkeit und Aktualit&auml;t der bereitgestellten kostenlosen und frei zug&auml;nglichen journalistischen Ratgeber und Nachrichten. Namentlich gekennzeichnete Beitr&auml;ge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des Anbieters wieder. Allein durch den Aufruf der kostenlosen und frei zug&auml;nglichen Inhalte kommt keinerlei Vertragsverh&auml;ltnis zwischen dem Nutzer und dem Anbieter zustande, insoweit fehlt es am Rechtsbindungswillen des Anbieters.<br />
<br />
&sect; 2 Externe Links<br />
Diese Website enth&auml;lt Verkn&uuml;pfungen zu Websites Dritter ("externe Links"). Diese Websites unterliegen der Haftung der jeweiligen Betreiber. Der Anbieter hat bei der erstmaligen Verkn&uuml;pfung der externen Links die fremden Inhalte daraufhin &uuml;berpr&uuml;ft, ob etwaige Rechtsverst&ouml;&szlig;e bestehen. Zu dem Zeitpunkt waren keine Rechtsverst&ouml;&szlig;e ersichtlich. Der Anbieter hat keinerlei Einfluss auf die aktuelle und zuk&uuml;nftige Gestaltung und auf die Inhalte der verkn&uuml;pften Seiten. Das Setzen von externen Links bedeutet nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. Eine st&auml;ndige Kontrolle der externen Links ist f&uuml;r den Anbieter ohne konkrete Hinweise auf Rechtsverst&ouml;&szlig;e nicht zumutbar. Bei Kenntnis von Rechtsverst&ouml;&szlig;en werden jedoch derartige externe Links unverz&uuml;glich gel&ouml;scht.<br />
<br />
&sect; 3 Urheber- und Leistungsschutzrechte<br />
Die auf dieser Website ver&ouml;ffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede vom deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters oder jeweiligen Rechteinhabers. Dies gilt insbesondere f&uuml;r Vervielf&auml;ltigung, Bearbeitung, &uuml;bersetzung, Einspeicherung, Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Inhalte und Rechte Dritter sind dabei als solche gekennzeichnet. Die unerlaubte Vervielf&auml;ltigung oder Weitergabe einzelner Inhalte oder kompletter Seiten ist nicht gestattet und strafbar. Lediglich die Herstellung von Kopien und Downloads f&uuml;r den pers&ouml;nlichen, privaten und nicht kommerziellen Gebrauch ist erlaubt.<br />
<br />
Die Darstellung dieser Website in fremden Frames ist nur mit schriftlicher Erlaubnis zul&auml;ssig.<br />
<br />
&sect; 4 Besondere Nutzungsbedingungen<br />
Soweit besondere Bedingungen f&uuml;r einzelne Nutzungen dieser Website von den vorgenannten Paragraphen abweichen, wird an entsprechender Stelle ausdr&uuml;cklich darauf hingewiesen. In diesem Falle gelten im jeweiligen Einzelfall die besonderen Nutzungsbedingungen.<p>Quelle: <a href="http://www.juraforum.de/impressum-generator/">Impressum-Generator</a> in Kooperation mit <a href="http://www.rechtsanwaelte-hannover.eu/rechtsgebiete/strafrecht/">Anwalt Strafrecht Hannover</a></p>

</div>
</body>
