<h1>Login</h1>

<?php 
	if ($anmeldestatus==true) {
		header ("refresh:0; url = /user/home");	
		exit;										 
	}
	
?>

<br><br>
<div class="center-block" style="width:300px" style="border-left: grey">
	<form class="form-horizontal" method="POST" action="login">

	<div class="form-group">
		<label class="control-label col-sm-2"> Benutzername </label>
		<div class="col-sm-3">
			<input type="text" class= "form-control" name="benutzername" required>
		</div>
	</div>	
	<div class="form-group">
		<label class="control-label col-sm-2"> Passwort </label>
		<div class="col-sm-3">
			<input type="password" class= "form-control" name="passwort" required>
		</div>
	</div>

<?php if (isset($inviteuser)) { ?>
	<input type='hidden' name="inviteuser" value='<?php echo $inviteuser?>'>
<?php }?>

<br><br>
<input type="submit" class="btn btn-default" value="Jetzt anmelden">


</form>
</div>
<br>

<a href="/user/passwordforgotten">Passwort vergessen?</a>

<?php 

if (isset($anmeldestatus) && $anmeldestatus==false) {
	echo "<center><b><font color='red'>Benutzername und Passwort stimmen nicht &uuml;berein!</font></b></center>";
}
?>