<h1>Login</h1>

<?php 
	if (isset ($anmeldestatus) && $anmeldestatus==true){
		header ("refresh:0; url = /user/home");
	}
	elseif (isset ($anmeldestatus) && $anmeldestatus==false) {
		echo "Benutzername und Passwort stimmen nicht &uuml;berein!";
	}

?>

<br><br>

<form method="POST" action="login">

<table>
<tr><td>Benutzername:</td><td> <input type="text" name="benutzername" required></td></tr>
<tr><td>Passwort:</td><td> <input type="password" name="passwort" required> </td></tr>
</table><br><br>
<input type="submit" value="Jetzt anmelden">


</form>
<br>

