<h1>Login</h1>

<?php 
	if ($anmeldestatus==true) {
		header ("refresh:0; url = /user/home");				//hier muss eine Weiterleitung auf die jeweilige "Homeseite" des Nutzers erfolgen! --> dazu homeAction ?? 
	}
	else{
		
		if ($anmeldestatus==false) {
			echo "<b>Benutzername und Passwort stimmen nicht &uuml;berein!</b>";
		}
	

?>

<br><br>

<form method="POST" action="login">

<table>
<tr><td>Benutzername:</td><td> <input type="text" name="benutzername" required></td></tr>
<tr><td>Passwort:</td><td> <input type="password" name="passwort" required> </td></tr>
</table><br><br>
<input type="submit" value="Jetzt anmelden">


</form>
<br>

<a href="/user/passwordforgotten">Passwort vergessen?</a>

<?php 

	}
?>