<h1>Passwort vergessen!</h1>

<?php if ($status == 'erfolgreich') { ?>
	
	<a>Passwort wurde erfolgreich ge&auml;ndert</a>

<?php 

header("refresh:2; url = /user/login");}
	
	else if (isset ($benutzer)) { ?>

		<form method="post" action="passwordforgotten">
		<table>
		<tr><td>Neues Passwort:</td><td> <input type="password" name="newPasswort1" required></td></tr>
		<tr><td>Neues Passwort best&auml;tigen:</td><td> <input type="password" name="newPasswort2" required></td></tr>
		</table>
		<input type="hidden" value = '<?php echo $benutzer ?>' name="benutzer">
		<br><br>
		<input type = "submit" value="Passwort jetzt &auml;ndern!"> 
		</form><br><br>

<?php 
	if ($status == 'ungleiche passwoerter') {
		
		echo "Das best&auml;tigte Passwort stimmt nicht mit dem neuen Passwort &uuml;berein.";
	  
		}
	}
	else {
?>

	<form method="post" action="passwordforgotten">
	<table>
	<tr><td>Benutzername</td><td> <input type="text" name="benutzermail" required></td></tr>
	</table>
	<br><br>
	<input type = "submit" value="E-Mail anfordern"> 
	</form><br><br>
	
	<?php if ($status == 'mail') {
		
		echo "E-Mail wurde an ihre Adresse versendet.";
		
	}?>

<?php }?>