<h1>Passwort vergessen!</h1>

<script type="text/javascript">

var form_mail = '<form method="post" action="passwordforgotten"><table>'
	+'<tr><td>E-Mail:</td><td> <input type="text" name="email" required></td></tr>'
	+'</table><br><br><input type = "submit" value="E-Mail anfordern"></form>';

var form_benutzer = '<form method="post" action="passwordforgotten"><table>'
+'<tr><td>Benutzername:</td><td> <input type="text" name="benutzername" required></td></tr>'
+'</table><br><br><input type = "submit" value="E-Mail anfordern"></form>';

function showmail() {

	document.getElementById("formular").innerHTML = form_mail;
	
}
function showbenutzer() {

	document.getElementById("formular").innerHTML = form_benutzer;
	
}

</script>



<?php if ($status == 'erfolgreich') { ?>
	
	<a>Passwort wurde erfolgreich ge&auml;ndert</a>
	
<?php 
	header("refresh:2; url = /user/login");
} 
	else if ($status == 'falsche pruefzahl') { ?>
	
	<a>Link ist veraltet! Bitte neuen anfordern!</a>


<?php 



header("refresh:2; url = /user/login");}
	
	else if (isset ($benutzer)) { ?>

		<form method="post" action="passwordforgotten">
		<table>
		<tr><td>Neues Passwort:</td><td> <input type="password" name="newPasswort1" required></td></tr>
		<tr><td>Neues Passwort best&auml;tigen:</td><td> <input type="password" name="newPasswort2" required></td></tr>
		</table>
		<input type="hidden" value = '<?php echo $benutzer ?>' name="benutzer">
		<input type="hidden" value = <?php echo $pruefzahl ?> name="pruefzahl">
		<br><br>
		<input type = "submit" value="Passwort jetzt &auml;ndern!"> 
		</form><br><br>

<?php 
	if ($status == 'ungleiche passwoerter') {
		
		echo "Das best&auml;tigte Passwort stimmt nicht mit dem neuen Passwort &uuml;berein.";
	  
		}
	}
	else {
?>
	
	<table><tr><td><button type="button" onclick="showmail()">E-Mail</button></td><td><button type="button" onclick="showbenutzer()">Benutzername</button></td></tr></table>
	<p id="formular">W&auml;hlen Sie aus E-Mail oder Benutzername aus.</p>
	<br><br>
	
	<?php if ($status == 'mail') {
		
		echo "E-Mail wurde an ihre Adresse versendet.";
		
	}?>

<?php }?>