<h1>Passwort vergessen!</h1>
<br><br>

<script type="text/javascript">

var form_mail = '<form class="form-horizontal" method="post" action="passwordforgotten">'
	+'<div class="form-group">'
	+'	<label class="control-label col-sm-2"> E-Mail</label>'
	+'	<div class="col-sm-3">'
	+'		<input type="text" class= "form-control" name="email" required>'
	+'	</div>'
	+'</div><br>'
	+'<input type = "submit" class="btn btn-default" value="E-Mail anfordern"></form>';

var form_benutzer = '<form class="form-horizontal" method="post" action="passwordforgotten">'
	+'<div class="form-group">'
	+'	<label class="control-label col-sm-2"> Benutzername</label>'
	+'	<div class="col-sm-3">'
	+'		<input type="text" class= "form-control" name="benutzername" required>'
	+'	</div>'
	+'</div><br>'
	+'<input type = "submit" class="btn btn-default" value="E-Mail anfordern"></form>';

function showmail() {

	document.getElementById("formular").innerHTML = form_mail;
	
}
function showbenutzer() {

	document.getElementById("formular").innerHTML = form_benutzer;
	
}

</script>



<?php if ($status == 'erfolgreich') { ?>
	
	<p style='color:green'><b> Passwort wurde erfolgreich ge&auml;ndert</b></p>
	
<?php 
	header("refresh:2; url = /user/login");
} 
	else if ($status == 'falsche pruefzahl') { ?>
	
	<p style='color:green'><b>Link ist veraltet! Bitte neu anfordern!</b></p>


<?php 



header("refresh:2; url = /user/login");}
	
	else if (isset ($benutzer)) { ?>

		<form class="form-horizontal" method="post" action="passwordforgotten">
		
		<div class="form-group">
			<label class="control-label col-sm-2"> Neues Passwort</label>
			<div class="col-sm-3">
				<input type="password" class= "form-control" name="newPasswort1" required>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-2"> Passwort erneut eingeben</label>
			<div class="col-sm-3">
				<input type="password" class= "form-control" name="newPasswort2" required>
			</div>
		</div>
		
		<input type="hidden" value = '<?php echo $benutzer ?>' name="benutzer">
		<input type="hidden" value = <?php echo $pruefzahl ?> name="pruefzahl">
		<br><br>
		<input type = "submit" class="btn btn-default" value="Passwort jetzt &auml;ndern!"> 
		</form><br><br>

<?php 
	if ($status == 'ungleiche passwoerter') {
		
		echo "<b><font color=red>Das best&auml;tigte Passwort stimmt nicht mit dem neuen Passwort &uuml;berein.</b></font>";
	  
		}
	}
	else {
?>
	
	<div class="btn-group">
	<button type="button" class="btn btn-primary" onclick="showmail()">E-Mail</button>
	<button type="button" class="btn btn-primary" onclick="showbenutzer()">Benutzername</button>
	</div>
	<br><br>
	<p id="formular">W&auml;hlen Sie aus E-Mail oder Benutzername aus.</p>
	<br><br>
	
	<?php if ($status == 'mail') {
		
		echo "<b><font color=green>E-Mail wurde an ihre Adresse versendet.</b></font>";
		
	}?>

<?php }?>