<h1>Registrierung</h1>


<form method='post' action='register'>

Benutzername: <input type="text" name="benutzername"> <br>
Passwort: <input type="text" name="passwort"> <br>
Vorname: <input type="text" name="vorname"> <br>
Nachname: <input type="text" name="nachname"> <br>
Geburtsdatum: <input type="text" name="geburtsdatum"> <br>
Strasse: <input type="text" name="strasse"> <br>
Postleitzahl: <input type="text" name="plz"> <br>
Ort: <input type="text" name="ort"> <br>
E-Mail: <input type="text" name="email"> <br>
<input type="hidden" value = 0 name="email_bestaetigt">
<input type="hidden" value = 0 name="ist_admin">
<input type="hidden" value = 0 name="ist_zertifizierer"> <br>
<input type="hidden" value = 1 name="ist_teilnehmer"> <br> <br>

<input type = "submit" value="Bestaetigen">

</form>