<?php if (isset($bestaetigt)) {?>
<div class="alert alert-danger" role="alert">
        <h2><b>Ihre Registrierung wurde bereits best&auml;tigt! ! Sie werden jetzt zum Login weitergeleitet.</b></h2>
</div>


<?php }else {?>
<div class="alert alert-success" role="alert">
    <h2><b>Registrierung erfolgreich best&auml;tigt! Sie werden jetzt zum Login weitergeleitet.</b></h2>
</div>




<?php } if (isset($benutzername)) {

	header("refresh:2; url=/kurs/enterkurs?benutzername=".$benutzername."&kurs_id=".$kurs_id);
	exit;

} else {?>

<?php 
header("refresh:2; url=/user/login"); 
exit;

}?>