<h1>Registrierung</h1>

<br><br>
<?php

if(isset($meldung)){
	$error = $meldung;
	echo $error;
}
if ($error == "Daten wurden erfolgreich gespeichert. Sie erhalten in K&uuml;rze eine E-Mail. Bitte folgen Sie dem darin enthaltenen Link, um Ihre Registrierung abzuschlie&szlig;en.") {
	header("refresh:2; url=/user/login");
}
else {
		
		
?>

<br><br>
<form method='post' action='register'>

<table>
<tr><td>Benutzername:</td><td> <input type="text" name="benutzername" required></td></tr>
<tr><td>Passwort:</td><td> <input type="text" name="passwort" required></td></tr>
<tr><td>Vorname:</td><td> <input type="text" name="vorname" required> </td></tr>
<tr><td>Nachname:</td><td> <input type="text" name="nachname" required></td></tr>
<tr><td>Geburtsdatum:</td><td> <input type="date" name="geburtsdatum" required></td></tr>
<tr><td>Strasse:</td><td> <input type="text" name="strasse" required></td></tr>
<tr><td>Postleitzahl:</td><td> <input type="text" name="plz" required></td></tr>
<tr><td>Ort:</td><td> <input type="text" name="ort" required></td></tr>
<tr><td>E-Mail:</td><td> <input type="email" name="email" required></td></tr>
</table>

<input type="hidden" value = 0 name="email_bestaetigt">


<!--  Hier kommt später noch ein if-Block hin. Anhand der Session wird geprüft ob hier ein Admin (besitzt Session) oder ein Teilnehmer eine Registrierung durchführt (besitzt natürlich keine Session)
      Admin verfügt über Auswahlmenü und kann entscheiden, welche Rolle er registrieren will -->
 <?php if ($status == 'admin') {?>
 
<tr><td>Rolle:</td><td><select name="rolle">
					   <option value='a'>Administrator</option>
					   <option value='z'>Zertifizierer</option>
					   <option value='t'>Teilnehmer</option></select>
</td></tr><br><br>

<?php } else {?>
      
<input type="hidden" value = 0 name="ist_admin">
<input type="hidden" value = 0 name="ist_zertifizierer"> 
<input type="hidden" value = 1 name="ist_teilnehmer"> <br> <br>

<?php }?>

<input type = "submit" value="Bestaetigen">

</form>


<?php 
}
?>
