<h1>Registrierung best&auml;tigen</h1>

<?php if (isset($bestaetigt)) { ?>
<div class="alert alert-danger" role="alert">
        <p>Ihre Registrierung wurde bereits best&auml;tigt! Sie werden jetzt zum Login weitergeleitet.</p>
</div>

<?php }else if (isset($pruefzahl)) {?>
<div class="alert alert-danger" role="alert">
        <p>Registrierung fehlgeschlagen!</p>
</div>


<?php }else { ?>
<div class="alert alert-success" role="alert">
    <p>Registrierung erfolgreich best&auml;tigt! Sie werden jetzt zum Login weitergeleitet.</p>
</div>




<?php } if (isset($benutzername)) {

	header("refresh:2; url=/kurs/enterkurs?benutzername=".$benutzername."&kurs_id=".$kurs_id);
	//exit;

} else { ?>

<?php 
header("refresh:2; url=/user/login"); 
//exit;

} ?>