<style>
#FragenListe {
	float:left;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 40%;
	padding: 2em;
	}

#Frage {
	padding: 2em;
	margin-left: 40%;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 60%;
	}
</style>
<div id="FragenListe">
	<h3>Fragen</h3>
	<table>
	<?php foreach ($fragen as $f) { ?>
			<tr><td><?=$f->getText()?></td><td><a href="<?= $this->url('frage', ['action' => 'answer', 'id' => $f->getId()]) ?>"><button type="button">Antworten</button></a></td><td>Flag, ob schon geantwortet</td></tr>		
	<?php } ?>
	</table>
</div>

<div id="Frage">
	<?php 
		echo $frage->getText();
		echo $frage->getPunkte();
		
		if ($frage->getTyp() == 'TF') {?>
		<form>
			<input type="hidden" name="typ" value="TF" >
			<input type="hidden" name="antwort_id" value="<?=$antworten[0]->getId()?>">
			<input type="radio"  name="tf" value="true"  <?php if ($antworten[0]->getStatus() == 1) echo "checked";?>> Wahr<br>
			<input type="radio"  name="tf" value="false" <?php if ($antworten[0]->getStatus() == 0) echo "checked";?>> Falsch<br>
			
			<input type="hidden" name="next_index" value=<?=$next_index + 1 //als Link??>>
			<input type="submit" name="speichern" value="Weiter">
		</form>	
		
		<?php }else {
			// <input type="hidden" name="typ" value="MC" >
			foreach ($antworten as $antwort) {?>
				Mc Frage...
		<?php	
			}
		}
	
	?>
	
</div>

<br>
<a href="<?= $this->url('pruefung', ['action' => 'result', 'id' => $schreibt_pruefung_id]) ?>"><button type="button">Prüfung beenden</button></a>