<style>
#FragenListe {
	float:left;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 40%;
	padding: 2em;
	}

#Frage {
	padding: 2em;
	margin-left: 40%;
	border: 5pt;
	border-color: black;
	border-style: solid;
	width: 60%;
	}
</style>
<div id="FragenListe">
	<h3>Fragen</h3>
	<table>
	<?php foreach ($fragen as $f) { ?>
			<tr><td><?=$f->getText()?></td><td><button type="button">Antworten</button></td><td>Flag, ob schon geantwortet</td></tr>		
	<?php } ?>
	</table>
</div>

<div id="Frage">
	<form>
	<?php 
		echo $frage->getText();
		echo '<br>Punkte: ' .$frage->getPunkte();
		
		if ($frage->getTyp() == 'TF') {?>
			<input type="hidden" name="typ" value="TF" >
			<input type="hidden" name="antwort_id" value="<?=$antworten[0]['antwort']->getId()?>">
			<input type="radio"  name="tf" value="true"  <?php if ($antworten[0]['status'] == 1) echo "checked";?>> Wahr<br>
			<input type="radio"  name="tf" value="false" <?php if ($antworten[0]['status'] == 0) echo "checked";?>> Falsch<br>
			
			
		
		<?php }else {
			echo '<input type="hidden" name="typ" value="MC">';
			foreach ($antworten as $antwort) {?>
				<br><?php echo $antwort['antwort']->getText();?>
				<input type="checkbox" name="check<?=$antwort['antwort']->getId()?>" <?php if ($antwort['status'] == 1) echo "checked";?>>
		<?php	
			}
		}
	?>
		<input type="hidden" name="next_index" value=<?=$next_index + 1?>>
		<input type="submit" name="speichern" value="Weiter">
	</form>	
</div>

<br>
<a href="<?= $this->url('pruefung', ['action' => 'result', 'id' => $schreibt_pruefung_id]) ?>"><button type="button">Prüfung beenden</button></a>