<?php 

use Zertifizierungstool\Model\User;

if(User::currentUser()->getBenutzername()!=NULL){

?>

<h1>Herzlich willkommen, <b><?php echo User::currentUser()->getBenutzername()?></b>!</h1>
<br>
<p style='font-size: 15'>	Sie befinden sich auf einem Portal zur pers&ouml;nlichen Weiterbildung. <br><br>
	Viel Spa&szlig; w&uuml;nscht Ihnen </p><br><br>

<div class="image-wrapper" align="center" >
<img src = "public/img/zert4tool.png" alt="Zert4Tool" width="80%">
</div>

<?php }
		else { ?>
		
		<h1>Herzlich Willkommen!</h1>
		<br>
		
		<p style='font-size: 15'>Sie befinden sich auf einem Portal zur pers&ouml;nlichen Weiterbildung. <br><br>
		
		W&auml;hlen Sie aus unseren verschiedenen Kursangeboten aus und lassen Sie sich durch unsere Partner zertifizieren! <br><br>
		Um zu starten, <b>loggen Sie sich ein</b> oder erstellen Sie <b>ein neues Benutzerkonto</b>.<br><br>
		Viel Spa&szlig; w&uuml;nscht Ihnen</p><br><br>
		
		<div class="image-wrapper" align="center" >
		<img src = "public/img/zert4tool.png" alt="Zert4Tool" width="80%">
		</div>
		
		<?php }?>
		


	
	



<br>
