<?php 

use Zertifizierungstool\Model\User;

if(User::currentUser()->getBenutzername()!=NULL){

?>

<h1>Herzlich willkommen, <b><?php echo User::currentUser()->getBenutzername()?></b>!</h1>
<br>
<p style='font-size: 15'>	Sie befinden sich auf einem Portal zur pers&ouml;nlichen Weiterbildung. <br><br>
	Team Zert4Tool w&uuml;nscht Ihnen viel Spa&szlig;!</p>


<?php }
		else { ?>
		
		<h1>Herzlich Willkommen!</h1>
		<br>
		
		<p style='font-size: 15'>Sie befinden sich auf einem Portal zur pers&ouml;nlichen Weiterbildung. <br><br>
		
		W&auml;hlen Sie aus unseren verschiedenen Kursangeboten aus und lassen Sie sich durch unsere Partner zertifizieren! <br><br>
		Um zu starten, <b>loggen Sie sich ein</b> oder erstellen Sie <b>ein neues Benutzerkonto</b>.<br><br>
		Team Zert4Tool w&uuml;nscht Ihnen viel Spa&szlig;!</p>
		
		<?php }?>
		
<?php if (strtotime("32.02.1990")!=false) {
echo "richtig";

} else 
{ echo "falsch";
}?>

	
	



<br>
